const en: string[] = [
  "Bamboo may bend, but wisdom remains rooted in the earth.",
  "The tree that offers the sweetest fruit is climbed by those who dare to reach.",
  "In stillness, we find our true nature; in play, we discover our joy.",
  "A gentle paw can move mountains when guided by patient determination.",
  "The wisest climb is not the fastest, but the one where each branch is cherished.",
  "Sleep when the sun is high, for the coolest thoughts come with the evening breeze.",
  "To share your bamboo is to multiply its sweetness tenfold.",
  "The forest teaches us that strength lies not in size, but in adaptability.",
  "The branch that holds you today was once a fragile shoot reaching for the sky.",
  "In the canopy of life, every creature finds their perfect height.",
  "A fluffy tail is nature's reminder that warmth comes from within.",
  "The river does not rush to the sea; neither should wisdom hurry to reveal itself.",
  "When the path grows steep, remember: even mountains rest in valleys.",
  "The sweetest berries grow where patience and sunlight meet.",
  "A single paw print in snow tells the story of a thousand careful steps.",
  "The wise tree-dweller knows that looking down is as important as looking up.",
  "In the quiet of morning mist, the forest whispers truths the day will hide.",
  "Every nap is a meditation; every stretch, a prayer to flexibility.",
  "The strongest grip is gentle enough to feel the heartbeat of the tree.",
  "Curiosity climbs higher than fear ever could.",
  "When two paths diverge in the bamboo grove, take the one less trampled.",
  "The moon sees all our midnight snacks and judges not.",
  "A warm branch shared is worth more than a perfect perch alone.",
  "Let your inner fire burn bright, even when your fur gets wet.",
  "The forest has no schedule, yet every season arrives on time.",
  "Balance is not standing still, but knowing when to sway with the wind.",
  "The smallest creature can cast the longest shadow when the light is right.",
  "Solitude in the treetops teaches what crowds on the ground cannot.",
  "He who naps with intention awakens with clarity. He who just naps also awakens, eventually.",
  "The universe provides bamboo, but you must still climb to reach it.",
  "A philosopher who cannot touch their toes has not yet mastered the art of reaching.",
  "Wisdom is knowing you're adorable; enlightenment is not letting it go to your head.",
  "The student asks: 'Master, what is the meaning of life?' The master replies: 'Have you tried napping on it?'",
  "In the depths of winter, I finally learned that within me there lay an invincible appetite.",
  "Do not mistake my climbing for fleeing; sometimes wisdom requires higher ground.",
  "The fool sees rain and complains. The wise see rain and find the driest branch.",
  "Those who say size doesn't matter have never tried to intimidate with a fluffy tail.",
  "Time spent grooming your tail is never wasted; presentability precedes credibility.",
  "If a tree falls in the forest and no red panda was napping in it, does it even matter?",
  "The path to enlightenment is long, winding, and best traveled with snacks.",
  "Before you judge another's choices, remember: you're not the one sleeping in their tree.",
  "The ancient texts speak of balance, but they forgot to mention that sometimes you just slip.",
  "True mastery is yawning without losing your grip on the branch.",
  "One cannot find inner peace on an empty stomach, nor outer peace while digesting.",
  "The greatest battles are fought not with claws, but with the strategic deployment of cuteness.",
  "Seek not to find yourself, but to lose yourself in the simple joy of a perfectly positioned sunbeam.",
  "The wise know that every expert was once a beginner who fell out of many trees.",
  "The forest does not compete; the tallest tree and smallest mushroom each have their place.",
  "A full belly and an empty mind: the beginning of true contentment.",
  "The branch does not ask if you are worthy; it simply holds or breaks. Choose your branches wisely.",
  "In the art of tree navigation, grace is simply falling with style.",
  "The moon does not worry about tomorrow's phase, nor should you fret about your next meal—though knowing where it is helps.",
  "Flexibility in body leads to flexibility in mind, and occasionally to impressive recoveries from near-falls.",
  "Morning brings new wisdom, but afternoon brings the perfect napping temperature.",
  "The loudest voice in the forest is not always the wisest; sometimes it's just hungry.",
  "To master the art of living, one must first master the art of comfortable positioning.",
  "The seasons change, the trees remain, and the patient panda outlasts all storms.",
  "A cluttered branch is a cluttered mind; simplicity knows where the good bamboo grows.",
  "The greatest teacher is experience; the second greatest is the consequence of poor branch selection.",
  "In moments of uncertainty, ask yourself: 'Would a nap help?' The answer is usually yes.",
  "The forest shares its abundance freely, but you still have to climb for it.",
  "Wisdom whispers while foolishness shouts, but a satisfied stomach speaks louder than both.",
  "The journey of life is really an upward spiral toward better sleeping spots.",
  "True courage is not the absence of fear, but climbing anyway despite the wobbly branch.",
  "The student seeks answers in books; the master seeks answers in bamboo groves and well-timed naps.",
  "Remember: today's impossible climb becomes tomorrow's favorite branch.",
  "The wise panda knows that being small is not a weakness when you're already at the top of the tree.",
];

const es: string[] = [
  "El bambú puede doblarse, pero la sabiduría permanece arraigada en la tierra.",
  "El árbol que ofrece el fruto más dulce es escalado por quienes se atreven a alcanzarlo.",
  "En la quietud encontramos nuestra verdadera naturaleza; en el juego, descubrimos nuestra alegría.",
  "Una pata suave puede mover montañas cuando la guía la determinación paciente.",
  "La escalada más sabia no es la más rápida, sino aquella donde cada rama es apreciada.",
  "Duerme cuando el sol está alto, pues los pensamientos más frescos llegan con la brisa de la tarde.",
  "Compartir tu bambú es multiplicar su dulzura diez veces.",
  "El bosque nos enseña que la fuerza no reside en el tamaño, sino en la adaptabilidad.",
  "La rama que te sostiene hoy fue una vez un brote frágil que alcanzaba el cielo.",
  "En el dosel de la vida, cada criatura encuentra su altura perfecta.",
  "Una cola esponjosa es el recordatorio de la naturaleza de que el calor viene desde adentro.",
  "El río no corre al mar; tampoco debería la sabiduría apresurarse a revelarse.",
  "Cuando el camino se empina, recuerda: hasta las montañas descansan en los valles.",
  "Las bayas más dulces crecen donde se encuentran la paciencia y la luz del sol.",
  "Una sola huella de pata en la nieve cuenta la historia de mil pasos cuidadosos.",
  "El sabio habitante de los árboles sabe que mirar hacia abajo es tan importante como mirar hacia arriba.",
  "En el silencio de la neblina matutina, el bosque susurra verdades que el día ocultará.",
  "Cada siesta es una meditación; cada estiramiento, una oración a la flexibilidad.",
  "El agarre más fuerte es lo suficientemente suave para sentir el latido del árbol.",
  "La curiosidad escala más alto de lo que el miedo podría jamás hacerlo.",
  "Cuando dos caminos se bifurcan en el bambuzal, toma el menos pisoteado.",
  "La luna ve todos nuestros bocadillos de medianoche y no juzga.",
  "Una rama cálida compartida vale más que una percha perfecta en soledad.",
  "Deja que tu fuego interior brille con fuerza, incluso cuando tu pelaje se moje.",
  "El bosque no tiene horario, pero cada estación llega puntual.",
  "El equilibrio no es quedarse quieto, sino saber cuándo mecerse con el viento.",
  "La criatura más pequeña puede proyectar la sombra más larga cuando la luz es perfecta.",
  "La soledad en las copas de los árboles enseña lo que las multitudes en el suelo no pueden.",
  "Quien duerme con intención despierta con claridad. Quien simplemente duerme también despierta, eventualmente.",
  "El universo provee bambú, pero aún debes escalar para alcanzarlo.",
  "Un filósofo que no puede tocarse los dedos del pie aún no ha dominado el arte de alcanzar.",
  "La sabiduría es saber que eres adorable; la iluminación es no dejar que se te suba a la cabeza.",
  "El estudiante pregunta: '¿Maestro, cuál es el significado de la vida?' El maestro responde: '¿Has intentado dormir una siesta sobre eso?'",
  "En lo más profundo del invierno, finalmente aprendí que dentro de mí yacía un apetito invencible.",
  "No confundas mi escalada con huida; a veces la sabiduría requiere terreno más elevado.",
  "El necio ve la lluvia y se queja. El sabio ve la lluvia y encuentra la rama más seca.",
  "Quienes dicen que el tamaño no importa nunca han intentado intimidar con una cola esponjosa.",
  "El tiempo dedicado a acicalar tu cola nunca se desperdicia; la presentabilidad precede a la credibilidad.",
  "Si un árbol cae en el bosque y ningún panda rojo estaba durmiendo en él, ¿realmente importa?",
  "El camino a la iluminación es largo, sinuoso y mejor recorrido con bocadillos.",
  "Antes de juzgar las elecciones de otro, recuerda: tú no eres quien duerme en su árbol.",
  "Los textos antiguos hablan de equilibrio, pero olvidaron mencionar que a veces simplemente te resbalas.",
  "La verdadera maestría es bostezar sin perder el agarre en la rama.",
  "Uno no puede encontrar la paz interior con el estómago vacío, ni la paz exterior mientras digiere.",
  "Las grandes batallas no se libran con garras, sino con el despliegue estratégico de la ternura.",
  "No busques encontrarte a ti mismo; piérdete en la simple alegría de un rayo de sol perfectamente posicionado.",
  "Los sabios saben que todo experto fue una vez un principiante que cayó de muchos árboles.",
  "El bosque no compite; el árbol más alto y el hongo más pequeño cada uno tiene su lugar.",
  "Vientre lleno y mente vacía: el comienzo del verdadero contentamiento.",
  "La rama no pregunta si eres digno; simplemente sostiene o se rompe. Elige tus ramas sabiamente.",
  "En el arte de navegar árboles, la gracia es simplemente caer con estilo.",
  "La luna no se preocupa por la fase de mañana, ni tú deberías angustiarte por tu próxima comida, aunque saber dónde está ayuda.",
  "La flexibilidad del cuerpo conduce a la flexibilidad de la mente, y ocasionalmente a recuperaciones impresionantes de casi caídas.",
  "La mañana trae nueva sabiduría, pero la tarde trae la temperatura perfecta para la siesta.",
  "La voz más alta en el bosque no siempre es la más sabia; a veces simplemente tiene hambre.",
  "Para dominar el arte de vivir, primero hay que dominar el arte del posicionamiento cómodo.",
  "Las estaciones cambian, los árboles permanecen, y el panda paciente sobrevive a todas las tormentas.",
  "Una rama desordenada es una mente desordenada; la simplicidad sabe dónde crece el buen bambú.",
  "El mayor maestro es la experiencia; el segundo mayor es la consecuencia de una mala selección de ramas.",
  "En momentos de incertidumbre, pregúntate: '¿Ayudaría una siesta?' La respuesta generalmente es sí.",
  "El bosque comparte su abundancia libremente, pero aún tienes que escalar para conseguirla.",
  "La sabiduría susurra mientras la necedad grita, pero un estómago satisfecho habla más fuerte que ambos.",
  "El viaje de la vida es realmente una espiral ascendente hacia mejores lugares para dormir.",
  "El verdadero coraje no es la ausencia del miedo, sino escalar de todas formas a pesar de la rama tambaleante.",
  "El estudiante busca respuestas en los libros; el maestro las busca en los bambuzales y las siestas bien programadas.",
  "Recuerda: la escalada imposible de hoy se convierte en la rama favorita de mañana.",
  "El panda sabio sabe que ser pequeño no es una debilidad cuando ya estás en la cima del árbol.",
];

const de: string[] = [
  "Bambus mag sich biegen, aber Weisheit bleibt in der Erde verwurzelt.",
  "Den Baum mit den süßesten Früchten erklimmen jene, die es wagen zu greifen.",
  "In der Stille finden wir unser wahres Wesen; im Spiel entdecken wir unsere Freude.",
  "Eine sanfte Pfote kann Berge versetzen, wenn sie von geduldiger Entschlossenheit geleitet wird.",
  "Die weiseste Klettertour ist nicht die schnellste, sondern jene, bei der jeder Ast gewürdigt wird.",
  "Schlafe wenn die Sonne hoch steht, denn die kühlsten Gedanken kommen mit dem Abendwind.",
  "Seinen Bambus zu teilen bedeutet, seine Süße zehnfach zu vervielfachen.",
  "Der Wald lehrt uns, dass Stärke nicht in der Größe liegt, sondern in der Anpassungsfähigkeit.",
  "Der Ast, der dich heute hält, war einst ein zarter Trieb, der nach dem Himmel strebte.",
  "Im Blätterdach des Lebens findet jedes Wesen seine perfekte Höhe.",
  "Ein flauschiger Schwanz ist die Erinnerung der Natur, dass Wärme von innen kommt.",
  "Der Fluss eilt nicht zum Meer; auch die Weisheit sollte es nicht eilig haben, sich zu zeigen.",
  "Wenn der Weg steiler wird, erinnere dich: Sogar Berge ruhen in Tälern.",
  "Die süßesten Beeren wachsen dort, wo Geduld und Sonnenlicht sich begegnen.",
  "Ein einzelner Pfotentapfen im Schnee erzählt die Geschichte von tausend behutsamen Schritten.",
  "Der weise Baumklettertier weiß, dass nach unten zu schauen genauso wichtig ist wie nach oben.",
  "In der Stille des Morgennebels flüstert der Wald Wahrheiten, die der Tag verbergen wird.",
  "Jedes Nickerchen ist eine Meditation; jedes Strecken ein Gebet an die Flexibilität.",
  "Der stärkste Griff ist sanft genug, um den Herzschlag des Baumes zu spüren.",
  "Neugier klettert höher, als die Angst es je könnte.",
  "Wenn sich zwei Pfade im Bambuswäldchen teilen, nimm den weniger ausgetretenen.",
  "Der Mond sieht all unsere mitternächtlichen Snacks und urteilt nicht.",
  "Ein geteilter warmer Ast ist mehr wert als ein perfekter Sitzplatz allein.",
  "Lass dein inneres Feuer hell leuchten, auch wenn dein Fell nass wird.",
  "Der Wald hat keinen Zeitplan, und doch kommt jede Jahreszeit pünktlich.",
  "Gleichgewicht ist nicht Stillstand, sondern zu wissen, wann man sich im Wind wiegt.",
  "Das kleinste Wesen kann den längsten Schatten werfen, wenn das Licht stimmt.",
  "Einsamkeit in den Baumwipfeln lehrt, was Menschenmassen am Boden nicht können.",
  "Wer mit Absicht schläft, erwacht mit Klarheit. Wer einfach schläft, erwacht auch, irgendwann.",
  "Das Universum stellt Bambus bereit, aber du musst noch klettern, um ihn zu erreichen.",
  "Ein Philosoph, der seine Zehen nicht berühren kann, hat die Kunst des Greifens noch nicht gemeistert.",
  "Weisheit ist zu wissen, dass du entzückend bist; Erleuchtung ist, es nicht zu Kopf steigen zu lassen.",
  "Der Schüler fragt: 'Meister, was ist der Sinn des Lebens?' Der Meister antwortet: 'Hast du versucht, darüber ein Nickerchen zu halten?'",
  "In der Tiefe des Winters erkannte ich schließlich, dass in mir ein unbesiegbarer Appetit schlummerte.",
  "Verwechsle mein Klettern nicht mit Flucht; manchmal erfordert Weisheit höheres Terrain.",
  "Der Narr sieht Regen und klagt. Der Weise sieht Regen und findet den trockensten Ast.",
  "Wer sagt, Größe spiele keine Rolle, hat noch nie versucht, mit einem flauschigen Schwanz einzuschüchtern.",
  "Zeit, die man damit verbringt, seinen Schwanz zu pflegen, ist nie verschwendet; Präsentabilität geht der Glaubwürdigkeit voraus.",
  "Wenn ein Baum im Wald fällt und kein roter Panda darin geschlafen hat, spielt es dann überhaupt eine Rolle?",
  "Der Weg zur Erleuchtung ist lang, kurvenreich und lässt sich am besten mit Snacks bereisen.",
  "Bevor du die Entscheidungen anderer bewertest, erinnere dich: Du schläfst nicht in ihrem Baum.",
  "Die alten Texte sprechen von Gleichgewicht, vergaßen aber zu erwähnen, dass man manchmal einfach ausrutscht.",
  "Wahre Meisterschaft ist es, zu gähnen ohne den Griff am Ast zu verlieren.",
  "Man kann keinen inneren Frieden auf leerem Magen finden, noch äußeren Frieden beim Verdauen.",
  "Die größten Kämpfe werden nicht mit Krallen geführt, sondern mit dem strategischen Einsatz von Niedlichkeit.",
  "Suche nicht danach, dich selbst zu finden; verliere dich in der schlichten Freude eines perfekt platzierten Sonnenstrahls.",
  "Die Weisen wissen, dass jeder Experte einst ein Anfänger war, der von vielen Bäumen fiel.",
  "Der Wald konkurriert nicht; der höchste Baum und der kleinste Pilz haben ihren Platz.",
  "Ein voller Bauch und ein leerer Geist: der Beginn wahren Zufriedenseins.",
  "Der Ast fragt nicht, ob du es verdient hast; er hält oder bricht einfach. Wähle deine Äste weise.",
  "In der Kunst der Baumnavigation ist Anmut einfach das Fallen mit Stil.",
  "Der Mond sorgt sich nicht um die Phase von morgen; auch du solltest dich nicht um deine nächste Mahlzeit sorgen – obwohl zu wissen, wo sie ist, hilft.",
  "Körperliche Flexibilität führt zu geistiger Flexibilität und gelegentlich zu beeindruckenden Erholungen nach Beinahe-Stürzen.",
  "Der Morgen bringt neue Weisheit, aber der Nachmittag bringt die perfekte Nickerchen-Temperatur.",
  "Die lauteste Stimme im Wald ist nicht immer die weiseste; manchmal hat sie einfach Hunger.",
  "Um die Kunst des Lebens zu meistern, muss man zunächst die Kunst der bequemen Positionierung meistern.",
  "Die Jahreszeiten wechseln, die Bäume bleiben, und der geduldige Panda überdauert alle Stürme.",
  "Ein unordentlicher Ast ist ein unordentlicher Geist; Einfachheit weiß, wo der gute Bambus wächst.",
  "Der größte Lehrer ist die Erfahrung; der zweitgrößte sind die Folgen schlechter Astauswahl.",
  "Frage dich in Momenten der Ungewissheit: 'Würde ein Nickerchen helfen?' Die Antwort ist meistens ja.",
  "Der Wald teilt seinen Reichtum frei, aber du musst noch klettern, um ihn zu bekommen.",
  "Weisheit flüstert, während Dummheit schreit, aber ein zufriedener Magen spricht lauter als beide.",
  "Die Lebensreise ist eigentlich eine aufwärts gerichtete Spirale zu besseren Schlafplätzen.",
  "Wahre Tapferkeit ist nicht die Abwesenheit von Angst, sondern trotzdem zu klettern, trotz des wackelnden Astes.",
  "Der Schüler sucht Antworten in Büchern; der Meister sucht sie in Bambuswäldern und gut getimten Nickerchen.",
  "Denke daran: Die unmögliche Klettertour von heute wird der Lieblingsast von morgen.",
  "Der weise Panda weiß, dass klein zu sein keine Schwäche ist, wenn man bereits an der Spitze des Baumes ist.",
];

const fr: string[] = [
  "Le bambou peut plier, mais la sagesse reste enracinée dans la terre.",
  "L'arbre qui offre les fruits les plus doux est gravi par ceux qui osent s'étirer pour les atteindre.",
  "Dans l'immobilité, nous trouvons notre vraie nature ; dans le jeu, nous découvrons notre joie.",
  "Une douce patte peut déplacer des montagnes guidée par une détermination patiente.",
  "L'ascension la plus sage n'est pas la plus rapide, mais celle où chaque branche est chérie.",
  "Dors quand le soleil est haut, car les pensées les plus fraîches viennent avec la brise du soir.",
  "Partager son bambou, c'est multiplier sa douceur par dix.",
  "La forêt nous enseigne que la force ne réside pas dans la taille, mais dans l'adaptabilité.",
  "La branche qui te soutient aujourd'hui était autrefois un fragile bourgeon aspirant vers le ciel.",
  "Dans la canopée de la vie, chaque créature trouve sa hauteur parfaite.",
  "Une queue touffue est le rappel de la nature que la chaleur vient de l'intérieur.",
  "Le fleuve ne se précipite pas vers la mer ; la sagesse non plus ne devrait pas se hâter de se révéler.",
  "Quand le chemin devient escarpé, souviens-toi : même les montagnes se reposent dans les vallées.",
  "Les baies les plus douces poussent là où la patience et le soleil se rencontrent.",
  "Une seule empreinte de patte dans la neige raconte l'histoire de mille pas prudents.",
  "Le sage grimpeur d'arbres sait que regarder vers le bas est aussi important que regarder vers le haut.",
  "Dans le calme de la brume matinale, la forêt chuchote des vérités que le jour cachera.",
  "Chaque sieste est une méditation ; chaque étirement, une prière à la souplesse.",
  "La prise la plus solide est assez douce pour sentir le battement de cœur de l'arbre.",
  "La curiosité grimpe plus haut que la peur ne le pourrait jamais.",
  "Quand deux chemins divergent dans la bambouseraie, prends celui le moins piétiné.",
  "La lune voit tous nos encas de minuit et ne juge pas.",
  "Une branche chaude partagée vaut plus qu'un perchoir parfait en solitaire.",
  "Laisse ton feu intérieur briller intensément, même quand ton pelage est mouillé.",
  "La forêt n'a pas d'horaire, pourtant chaque saison arrive à temps.",
  "L'équilibre n'est pas l'immobilité, mais savoir quand se balancer avec le vent.",
  "La plus petite créature peut projeter la plus longue ombre quand la lumière est juste.",
  "La solitude dans les cimes enseigne ce que les foules au sol ne peuvent pas.",
  "Celui qui fait une sieste avec intention s'éveille avec clarté. Celui qui fait simplement une sieste s'éveille aussi, éventuellement.",
  "L'univers fournit le bambou, mais tu dois quand même grimper pour l'atteindre.",
  "Un philosophe qui ne peut pas toucher ses orteils n'a pas encore maîtrisé l'art d'atteindre.",
  "La sagesse c'est de savoir qu'on est adorable ; l'illumination c'est ne pas la laisser monter à la tête.",
  "L'élève demande : 'Maître, quel est le sens de la vie ?' Le maître répond : 'As-tu essayé de faire une sieste dessus ?'",
  "Dans les profondeurs de l'hiver, j'ai finalement appris qu'en moi sommeillait un appétit invincible.",
  "Ne confonds pas mon escalade avec une fuite ; parfois la sagesse nécessite un terrain plus élevé.",
  "Le fou voit la pluie et se plaint. Le sage voit la pluie et trouve la branche la plus sèche.",
  "Ceux qui disent que la taille n'a pas d'importance n'ont jamais essayé d'intimider avec une queue touffue.",
  "Le temps consacré à se lisser la queue n'est jamais perdu ; la présentation précède la crédibilité.",
  "Si un arbre tombe dans la forêt et qu'aucun panda roux n'y dormait, est-ce que ça compte vraiment ?",
  "Le chemin vers l'illumination est long, sinueux, et mieux parcouru avec des en-cas.",
  "Avant de juger les choix d'autrui, souviens-toi : tu n'es pas celui qui dort dans son arbre.",
  "Les anciens textes parlent d'équilibre, mais ils ont oublié de mentionner qu'on glisse parfois.",
  "La vraie maîtrise, c'est bâiller sans perdre sa prise sur la branche.",
  "On ne peut pas trouver la paix intérieure le ventre vide, ni la paix extérieure en digérant.",
  "Les plus grandes batailles ne se mènent pas avec des griffes, mais avec le déploiement stratégique de la mignonnerie.",
  "Ne cherche pas à te trouver ; perds-toi dans la simple joie d'un rayon de soleil parfaitement positionné.",
  "Les sages savent que chaque expert était autrefois un débutant qui est tombé de nombreux arbres.",
  "La forêt ne rivalise pas ; le plus grand arbre et le plus petit champignon ont chacun leur place.",
  "Un ventre plein et un esprit vide : le début du vrai contentement.",
  "La branche ne demande pas si tu en es digne ; elle tient ou cède simplement. Choisis tes branches sagement.",
  "Dans l'art de naviguer les arbres, la grâce c'est simplement tomber avec style.",
  "La lune ne s'inquiète pas de sa phase demain, et tu ne devrais pas t'inquiéter de ton prochain repas — bien que savoir où il se trouve aide.",
  "La flexibilité du corps mène à la flexibilité de l'esprit, et parfois à de remarquables récupérations après des quasi-chutes.",
  "Le matin apporte de nouvelles sagesses, mais l'après-midi apporte la température parfaite pour la sieste.",
  "La voix la plus forte dans la forêt n'est pas toujours la plus sage ; parfois elle a juste faim.",
  "Pour maîtriser l'art de vivre, il faut d'abord maîtriser l'art du positionnement confortable.",
  "Les saisons changent, les arbres demeurent, et le panda patient survit à toutes les tempêtes.",
  "Une branche encombrée est un esprit encombré ; la simplicité sait où pousse le bon bambou.",
  "Le plus grand professeur est l'expérience ; le deuxième est la conséquence d'un mauvais choix de branche.",
  "Dans les moments d'incertitude, demande-toi : 'Une sieste aiderait-elle ?' La réponse est généralement oui.",
  "La forêt partage son abondance librement, mais tu dois quand même grimper pour l'obtenir.",
  "La sagesse chuchote tandis que la sottise crie, mais un estomac satisfait parle plus fort que les deux.",
  "Le voyage de la vie est en réalité une spirale ascendante vers de meilleurs spots pour dormir.",
  "Le vrai courage n'est pas l'absence de peur, mais grimper quand même malgré la branche branlante.",
  "L'élève cherche des réponses dans les livres ; le maître les cherche dans les bambouseraies et les siestes bien placées.",
  "Souviens-toi : l'escalade impossible d'aujourd'hui devient la branche préférée de demain.",
  "Le panda sage sait qu'être petit n'est pas une faiblesse quand on est déjà au sommet de l'arbre.",
];

const zh: string[] = [
  "竹子可以弯曲，但智慧扎根于大地。",
  "能摘到最甜果实的树，由勇于攀登的人来爬。",
  "在静止中，我们找到真实的自我；在嬉戏中，我们发现喜悦。",
  "轻柔的爪子在耐心的决心引导下，也能移动山岳。",
  "最智慧的攀登不是最快的，而是珍惜每一根树枝的那种。",
  "当太阳高悬时入睡，因为最清凉的思绪随着傍晚的微风而来。",
  "分享你的竹子，其甜蜜便会增加十倍。",
  "森林教导我们，力量不在于大小，而在于适应能力。",
  "今天支撑你的树枝，曾经是伸向天空的脆弱嫩芽。",
  "在生命的林冠中，每个生灵都能找到自己完美的高度。",
  "蓬松的尾巴是大自然提醒我们：温暖来自内心。",
  "河流不急于奔向大海；智慧也不应急于显现。",
  "当道路变得陡峭时，记住：即使是山也在山谷中休息。",
  "最甜的浆果生长在耐心与阳光交汇之处。",
  "雪地上的一个爪印，讲述了千步谨慎前行的故事。",
  "智慧的树居者知道，向下看与向上看同样重要。",
  "在晨雾的宁静中，森林低语着白昼将要隐藏的真相。",
  "每次小憩都是冥想；每次伸展，都是对柔韧性的祈祷。",
  "最强的握力轻柔到足以感受树的心跳。",
  "好奇心攀登的高度超过恐惧所能达到的。",
  "当两条路在竹林中分叉时，选择那条少有人踏足的。",
  "月亮看见我们所有的午夜零食，却不加评判。",
  "共享一根温暖的树枝，胜过独占一个完美的栖息处。",
  "让你内心的火焰明亮燃烧，即使你的毛皮被淋湿。",
  "森林没有时间表，但每个季节都准时到来。",
  "平衡不是静止不动，而是知道何时随风摇摆。",
  "当光线恰到好处时，最小的生物也能投下最长的影子。",
  "树梢上的独处，能教会地面人群所无法传授的东西。",
  "怀着意图小憩的人，醒来时思路清晰。只是小憩的人也会醒来，终究。",
  "宇宙提供竹子，但你仍需攀登才能够到。",
  "一个无法触碰脚趾的哲学家，还未掌握伸展的艺术。",
  "智慧是知道自己可爱；觉悟是不让它冲昏头脑。",
  "学生问：'师父，生命的意义是什么？'师父回答：'你有没有试过睡一觉想想看？'",
  "在严冬的深处，我终于明白：我内心藏着一种无法征服的食欲。",
  "不要把我的攀登误认为是逃跑；有时智慧需要更高的立足点。",
  "愚者见雨而抱怨。智者见雨而寻找最干燥的树枝。",
  "说大小不重要的人，从未试过用蓬松的尾巴来震慑他人。",
  "花时间梳理你的尾巴从不是浪费；得体先于可信。",
  "如果一棵树在森林中倒下，而没有小熊猫在其中打盹，这重要吗？",
  "通往觉悟的道路漫长曲折，最好带着零食前行。",
  "在评判他人的选择之前，记住：你并不是睡在他们树上的那个。",
  "古老文本谈到了平衡，但忘记提及有时你就是会滑倒。",
  "真正的精通是打哈欠而不失去对树枝的抓握。",
  "空腹难觅内心平静，消化时难觅外在宁静。",
  "最伟大的战役不用爪子，而用可爱的战略性展示来进行。",
  "不要寻求找到自己；在一缕完美定位的阳光中迷失自己的简单喜悦。",
  "智者知道每个专家曾经都是从许多树上跌落的初学者。",
  "森林不竞争；最高的树和最小的蘑菇各有其位置。",
  "吃饱喝足，心无杂念：真正满足的开始。",
  "树枝不问你是否值得；它只是承载或折断。明智地选择你的树枝。",
  "在树木导航的艺术中，优雅就是带着风格坠落。",
  "月亮不担心明天的相位，你也不必为下一餐发愁——尽管知道它在哪里会有帮助。",
  "身体的柔韧性带来心灵的柔韧性，偶尔也带来从险些跌倒中令人印象深刻的恢复。",
  "早晨带来新的智慧，但下午带来完美的打盹温度。",
  "森林中最响亮的声音不总是最智慧的；有时它只是饿了。",
  "要掌握生活的艺术，必须先掌握舒适定位的艺术。",
  "季节更替，树木长存，耐心的熊猫比一切风暴都更长久。",
  "凌乱的树枝是凌乱的心灵；简单知道好竹子在哪里生长。",
  "最伟大的老师是经验；第二伟大的是选错树枝的后果。",
  "在不确定的时刻，问问自己：'打个盹会有帮助吗？'答案通常是肯定的。",
  "森林慷慨地分享其丰盛，但你仍需攀登才能得到。",
  "智慧低语，愚蠢高喊，但满足的胃说话声比两者都响。",
  "生命的旅程实际上是朝着更好睡眠之所的向上螺旋。",
  "真正的勇气不是没有恐惧，而是尽管树枝摇晃仍然攀登。",
  "学生在书中寻找答案；师父在竹林和适时的小憩中寻找答案。",
  "记住：今天看似不可能的攀登，明天就会成为最喜欢的树枝。",
  "智慧的熊猫知道，当你已经站在树顶时，个子小不是弱点。",
];

const hi: string[] = [
  "बाँस झुक सकता है, लेकिन ज्ञान धरती में जड़ा रहता है।",
  "सबसे मीठे फल वाले पेड़ पर वही चढ़ता है जो पहुँचने का साहस करता है।",
  "शांति में हम अपना सच्चा स्वभाव पाते हैं; खेल में हम अपनी खुशी खोजते हैं।",
  "एक कोमल पंजा पहाड़ों को हिला सकता है जब उसे धैर्यपूर्ण दृढ़ता मार्गदर्शन दे।",
  "सबसे बुद्धिमान चढ़ाई सबसे तेज़ नहीं, बल्कि वह है जिसमें हर शाखा को सराहा जाए।",
  "जब सूरज ऊंचा हो तब सोओ, क्योंकि सबसे ठंडे विचार शाम की हवा के साथ आते हैं।",
  "अपना बाँस बाँटना उसकी मिठास को दस गुना बढ़ाना है।",
  "जंगल हमें सिखाता है कि ताकत आकार में नहीं, अनुकूलनशीलता में है।",
  "जो शाखा आज तुम्हें थामे है, कभी वह आसमान की ओर बढ़ती नाजुक कोपल थी।",
  "जीवन की छतरी में, हर प्राणी अपनी सही ऊँचाई पाता है।",
  "एक फूली हुई पूँछ प्रकृति की याद दिलाती है कि गर्माहट भीतर से आती है।",
  "नदी समुद्र की ओर नहीं भागती; ज्ञान को भी खुद को प्रकट करने की जल्दी नहीं होनी चाहिए।",
  "जब रास्ता खड़ा हो जाए, याद करो: पहाड़ भी घाटियों में विश्राम करते हैं।",
  "सबसे मीठे जामुन वहाँ उगते हैं जहाँ धैर्य और धूप मिलती है।",
  "बर्फ में एक पंजे का निशान हजार सावधान कदमों की कहानी कहता है।",
  "पेड़ों पर रहने वाला बुद्धिमान जानता है कि नीचे देखना उतना ही जरूरी है जितना ऊपर।",
  "सुबह की धुंध की शांति में, जंगल वो सत्य फुसफुसाता है जो दिन छुपा देगा।",
  "हर झपकी एक ध्यान है; हर खिंचाव, लचीलेपन की एक प्रार्थना।",
  "सबसे मजबूत पकड़ इतनी कोमल है कि पेड़ की धड़कन महसूस हो सके।",
  "जिज्ञासा उतनी ऊँची चढ़ती है जितना डर कभी नहीं चढ़ सकता।",
  "जब बाँस के जंगल में दो रास्ते अलग हों, वह लो जो कम रौंदा गया हो।",
  "चाँद हमारे सब आधी रात के नाश्ते देखता है और फैसला नहीं करता।",
  "साझा की गई एक गर्म शाखा अकेले के एकदम सही बसेरे से ज्यादा मूल्यवान है।",
  "अपनी आंतरिक अग्नि को तेज़ जलने दो, भले ही तुम्हारा फर भीग जाए।",
  "जंगल का कोई कार्यक्रम नहीं, फिर भी हर मौसम समय पर आता है।",
  "संतुलन स्थिर खड़े रहना नहीं है, बल्कि यह जानना है कि हवा के साथ कब झूलना है।",
  "सबसे छोटा प्राणी सबसे लंबी छाया डाल सकता है जब रोशनी सही हो।",
  "पेड़ों की चोटी पर एकांत वह सिखाता है जो नीचे भीड़ नहीं सिखा सकती।",
  "इरादे से सोने वाला स्पष्टता के साथ जागता है। बस सोने वाला भी जागता है, आखिरकार।",
  "ब्रह्मांड बाँस प्रदान करता है, लेकिन तुम्हें फिर भी उस तक पहुँचने के लिए चढ़ना होगा।",
  "एक दार्शनिक जो अपने पैर की उँगलियाँ नहीं छू सकता, उसने अभी तक पहुँचने की कला में महारत हासिल नहीं की।",
  "ज्ञान यह जानना है कि तुम प्यारे हो; आत्मज्ञान है इसे सिर पर न चढ़ने देना।",
  "शिष्य पूछता है: 'गुरुजी, जीवन का अर्थ क्या है?' गुरु उत्तर देते हैं: 'क्या तुमने इस पर एक झपकी लेने की कोशिश की है?'",
  "सर्दियों की गहराई में, मैंने अंततः सीखा कि मेरे भीतर एक अजेय भूख छिपी है।",
  "मेरी चढ़ाई को भागने मत समझो; कभी-कभी ज्ञान को ऊँची ज़मीन की ज़रूरत होती है।",
  "मूर्ख बारिश देखकर शिकायत करता है। बुद्धिमान बारिश देखकर सबसे सूखी शाखा ढूंढता है।",
  "जो कहते हैं आकार मायने नहीं रखता, उन्होंने कभी फूली पूँछ से डराने की कोशिश नहीं की।",
  "अपनी पूँछ सँवारने में लगाया समय कभी बर्बाद नहीं होता; प्रस्तुति विश्वसनीयता से पहले आती है।",
  "अगर जंगल में एक पेड़ गिरे और उसमें कोई लाल पांडा न सो रहा हो, तो क्या यह मायने रखता है?",
  "ज्ञान का मार्ग लंबा, टेढ़ा-मेढ़ा और नाश्ते के साथ सबसे अच्छा तय होता है।",
  "दूसरों के चुनावों का न्याय करने से पहले याद करो: तुम उनके पेड़ में नहीं सो रहे।",
  "प्राचीन ग्रंथ संतुलन की बात करते हैं, लेकिन यह उल्लेख करना भूल गए कि कभी-कभी तुम बस फिसल जाते हो।",
  "सच्ची महारत बिना शाखा की पकड़ खोए जम्हाई लेना है।",
  "खाली पेट आंतरिक शांति नहीं मिल सकती, न पाचन के दौरान बाहरी शांति।",
  "सबसे बड़ी लड़ाइयाँ पंजों से नहीं लड़ी जाती, बल्कि प्यारेपन के रणनीतिक प्रदर्शन से।",
  "खुद को ढूंढने की कोशिश मत करो; एकदम सही स्थान पर धूप की साधारण खुशी में खुद को खो दो।",
  "बुद्धिमान जानते हैं कि हर विशेषज्ञ एक बार कई पेड़ों से गिरने वाला शुरुआती था।",
  "जंगल प्रतिस्पर्धा नहीं करता; सबसे ऊँचे पेड़ और सबसे छोटे मशरूम दोनों की अपनी जगह है।",
  "भरा हुआ पेट और खाली मन: सच्ची संतुष्टि की शुरुआत।",
  "शाखा नहीं पूछती कि तुम योग्य हो या नहीं; वह बस थामती है या टूटती है। अपनी शाखाएं बुद्धिमानी से चुनो।",
  "पेड़ नेविगेशन की कला में, कृपा बस शैली के साथ गिरना है।",
  "चाँद कल की अवस्था की चिंता नहीं करता; न ही तुम्हें अगले भोजन की चिंता करनी चाहिए — हालांकि यह जानना कि वह कहाँ है, मदद करता है।",
  "शरीर का लचीलापन मन के लचीलेपन की ओर ले जाता है, और कभी-कभी लगभग गिरने से प्रभावशाली वापसी की ओर।",
  "सुबह नया ज्ञान लाती है, लेकिन दोपहर आदर्श झपकी तापमान लाती है।",
  "जंगल में सबसे तेज़ आवाज़ हमेशा सबसे बुद्धिमान नहीं होती; कभी-कभी वह बस भूखी होती है।",
  "जीवन की कला में महारत पाने के लिए, पहले आरामदायक स्थिति की कला में महारत पाना होगा।",
  "मौसम बदलते हैं, पेड़ रहते हैं, और धैर्यवान पांडा सब तूफानों से ज्यादा टिकाऊ है।",
  "अस्त-व्यस्त शाखा अस्त-व्यस्त मन है; सरलता जानती है कि अच्छा बाँस कहाँ उगता है।",
  "सबसे बड़े शिक्षक अनुभव हैं; दूसरे सबसे बड़े शाखा के बुरे चुनाव के परिणाम हैं।",
  "अनिश्चितता के क्षणों में खुद से पूछो: 'क्या एक झपकी मदद करेगी?' जवाब आमतौर पर हाँ होता है।",
  "जंगल अपनी प्रचुरता मुक्त रूप से साझा करता है, लेकिन तुम्हें अभी भी उसके लिए चढ़ना होगा।",
  "ज्ञान फुसफुसाता है जबकि मूर्खता चिल्लाती है, लेकिन संतुष्ट पेट दोनों से ज़ोर से बोलता है।",
  "जीवन की यात्रा वास्तव में बेहतर नींद की जगहों की ओर एक ऊपर की ओर सर्पिल है।",
  "सच्ची वीरता डर का अभाव नहीं है, बल्कि हिलती शाखा के बावजूद चढ़ना है।",
  "शिष्य किताबों में जवाब ढूंढता है; गुरु बाँस के जंगलों और सही समय की झपकी में।",
  "याद रखो: आज की असंभव चढ़ाई कल की पसंदीदा शाखा बन जाती है।",
  "बुद्धिमान पांडा जानता है कि छोटा होना कोई कमजोरी नहीं जब तुम पहले से ही पेड़ की चोटी पर हो।",
];

const it: string[] = [
  "Il bambù può piegarsi, ma la saggezza rimane radicata nella terra.",
  "L'albero che offre i frutti più dolci viene scalato da chi osa tendere la mano.",
  "Nell'immobilità troviamo la nostra vera natura; nel gioco scopriamo la nostra gioia.",
  "Una zampa gentile può spostare le montagne quando è guidata da una determinazione paziente.",
  "La scalata più saggia non è la più veloce, ma quella in cui ogni ramo è apprezzato.",
  "Dormi quando il sole è alto, perché i pensieri più freschi arrivano con la brezza serale.",
  "Condividere il tuo bambù significa moltiplicare la sua dolcezza per dieci.",
  "La foresta ci insegna che la forza non risiede nella dimensione, ma nell'adattabilità.",
  "Il ramo che ti sostiene oggi era una volta un fragile germoglio che tendeva verso il cielo.",
  "Nella chioma della vita, ogni creatura trova la sua altezza perfetta.",
  "Una coda soffice è il promemoria della natura che il calore viene dall'interno.",
  "Il fiume non si affretta verso il mare; nemmeno la saggezza dovrebbe affrettarsi a rivelarsi.",
  "Quando il cammino diventa ripido, ricorda: persino le montagne riposano nelle valli.",
  "Le bacche più dolci crescono dove la pazienza e la luce del sole si incontrano.",
  "Una singola impronta di zampa nella neve racconta la storia di mille passi attenti.",
  "Il saggio abitatore degli alberi sa che guardare in basso è importante quanto guardare in alto.",
  "Nel silenzio della nebbia mattutina, la foresta sussurra verità che il giorno nasconderà.",
  "Ogni pisolino è una meditazione; ogni stiracchiamento, una preghiera alla flessibilità.",
  "La presa più forte è abbastanza dolce da sentire il battito cardiaco dell'albero.",
  "La curiosità scala più in alto di quanto la paura potrebbe mai fare.",
  "Quando due sentieri divergono nel boschetto di bambù, prendi quello meno battuto.",
  "La luna vede tutti i nostri spuntini di mezzanotte e non giudica.",
  "Un ramo caldo condiviso vale più di un posatoi perfetto da soli.",
  "Lascia che il tuo fuoco interiore bruci intensamente, anche quando la tua pelliccia si bagna.",
  "La foresta non ha orari, eppure ogni stagione arriva puntuale.",
  "L'equilibrio non è stare fermi, ma sapere quando ondeggiare con il vento.",
  "La creatura più piccola può proiettare l'ombra più lunga quando la luce è giusta.",
  "La solitudine in cima agli alberi insegna ciò che le folle a terra non possono.",
  "Chi fa un pisolino con intenzione si sveglia con chiarezza. Chi fa solo un pisolino si sveglia anche lui, alla fine.",
  "L'universo fornisce il bambù, ma devi comunque scalare per raggiungerlo.",
  "Un filosofo che non riesce a toccarsi le dita dei piedi non ha ancora padroneggiato l'arte di tendere la mano.",
  "La saggezza è sapere di essere adorabili; l'illuminazione è non lasciarselo montare alla testa.",
  "Lo studente chiede: 'Maestro, qual è il significato della vita?' Il maestro risponde: 'Hai provato a farci un pisolino sopra?'",
  "Nelle profondità dell'inverno, ho finalmente imparato che dentro di me c'era un appetito invincibile.",
  "Non confondere la mia scalata con la fuga; a volte la saggezza richiede un terreno più elevato.",
  "Lo stolto vede la pioggia e si lamenta. Il saggio vede la pioggia e trova il ramo più asciutto.",
  "Chi dice che le dimensioni non contano non ha mai provato a intimidire con una coda soffice.",
  "Il tempo dedicato a curare la tua coda non è mai sprecato; la presentabilità precede la credibilità.",
  "Se un albero cade nella foresta e nessun panda rosso vi stava dormendo, conta davvero?",
  "Il cammino verso l'illuminazione è lungo, tortuoso e meglio percorso con degli snack.",
  "Prima di giudicare le scelte degli altri, ricorda: non sei tu quello che dorme nel loro albero.",
  "I testi antichi parlano di equilibrio, ma si sono dimenticati di menzionare che a volte si scivola semplicemente.",
  "La vera maestria è sbadigliare senza perdere la presa sul ramo.",
  "Non si può trovare la pace interiore a stomaco vuoto, né la pace esteriore mentre si digerisce.",
  "Le più grandi battaglie non si combattono con gli artigli, ma con il dispiegamento strategico della tenerezza.",
  "Non cercare di trovare te stesso; perditi nella semplice gioia di un raggio di sole perfettamente posizionato.",
  "I saggi sanno che ogni esperto era una volta un principiante che è caduto da molti alberi.",
  "La foresta non compete; l'albero più alto e il fungo più piccolo hanno ciascuno il loro posto.",
  "Pancia piena e mente vuota: l'inizio del vero appagamento.",
  "Il ramo non chiede se sei degno; semplicemente regge o si spezza. Scegli i tuoi rami con saggezza.",
  "Nell'arte di navigare tra gli alberi, la grazia è semplicemente cadere con stile.",
  "La luna non si preoccupa della sua fase di domani, né tu dovresti angosciarti per il tuo prossimo pasto — anche se sapere dove si trova aiuta.",
  "La flessibilità del corpo porta alla flessibilità della mente, e a volte a impressionanti recuperi da quasi-cadute.",
  "Il mattino porta nuova saggezza, ma il pomeriggio porta la temperatura perfetta per il pisolino.",
  "La voce più alta nella foresta non è sempre la più saggia; a volte ha solo fame.",
  "Per padroneggiare l'arte di vivere, bisogna prima padroneggiare l'arte del posizionamento comodo.",
  "Le stagioni cambiano, gli alberi rimangono, e il panda paziente sopravvive a tutte le tempeste.",
  "Un ramo disordinato è una mente disordinata; la semplicità sa dove cresce il buon bambù.",
  "Il più grande insegnante è l'esperienza; il secondo è la conseguenza di una cattiva scelta di rami.",
  "Nei momenti di incertezza, chiediti: 'Un pisolino aiuterebbe?' La risposta è di solito sì.",
  "La foresta condivide la sua abbondanza liberamente, ma devi comunque scalare per ottenerla.",
  "La saggezza sussurra mentre la stupidità urla, ma uno stomaco soddisfatto parla più forte di entrambe.",
  "Il viaggio della vita è in realtà una spirale ascendente verso posti migliori dove dormire.",
  "Il vero coraggio non è l'assenza della paura, ma scalare comunque nonostante il ramo traballante.",
  "Lo studente cerca risposte nei libri; il maestro le cerca nei boschetti di bambù e nei pisolini ben programmati.",
  "Ricorda: la scalata impossibile di oggi diventa il ramo preferito di domani.",
  "Il panda saggio sa che essere piccolo non è una debolezza quando sei già in cima all'albero.",
];

const ja: string[] = [
  "竹は曲がるかもしれないが、知恵は大地に根ざしている。",
  "最も甘い果実をつける木に登るのは、手を伸ばす勇気のある者だ。",
  "静けさの中に本当の自分を見つけ、遊びの中に喜びを発見する。",
  "忍耐強い決意に導かれた優しい前足は、山をも動かせる。",
  "最も賢い登り方は最も速いものではなく、各枝を大切にするものだ。",
  "太陽が高い時に眠りなさい、最も涼しい思考は夕べの風と共にやってくる。",
  "あなたの竹を分かち合うことは、その甘さを十倍にすることだ。",
  "森は私たちに、力は大きさではなく適応力にあることを教える。",
  "今日あなたを支えている枝は、かつて空に向かって伸びる細い芽だった。",
  "生命の林冠の中で、すべての生き物が完璧な高さを見つける。",
  "ふわふわの尻尾は、温もりは内側から来るという自然の思い出させ。",
  "川は海へと急がない。知恵も自らを現すことを急いではいけない。",
  "道が険しくなった時、思い出しなさい：山でさえ谷で休む。",
  "最も甘い実は、忍耐と陽光が出会う場所に育つ。",
  "雪の中の一つの前足の跡は、千の慎重な一歩の物語を語る。",
  "賢い木の住人は、下を見ることが上を見ることと同様に重要だと知っている。",
  "朝の霧の静けさの中で、森は昼間が隠す真実をささやく。",
  "每回の昼寝は瞑想であり、毎回の伸びは柔軟性への祈りだ。",
  "最も強い握りは、木の鼓動を感じられるほど優しい。",
  "好奇心は恐れが決して届かない高さまで登る。",
  "竹林で二つの道が分かれる時、あまり踏まれていない道を選べ。",
  "月は私たちの深夜のおやつを全部見ているが、裁かない。",
  "分け合った温かい枝は、一人占めの完璧な止まり木より価値がある。",
  "内なる炎を明るく燃やし続けなさい、たとえ毛皮が濡れても。",
  "森には予定がないが、それでも毎季節が時間通りに訪れる。",
  "バランスとは動かないことではなく、いつ風に揺れるかを知ることだ。",
  "光が適切な時、最も小さな生き物が最も長い影を落とすことができる。",
  "木の頂での孤独は、地上の群衆が教えられないことを教えてくれる。",
  "意図を持って昼寝する者は明晰に目覚める。ただ昼寝する者も目覚める、やがて。",
  "宇宙は竹を提供するが、それでもあなたは届くために登らなければならない。",
  "つま先に触れられない哲学者は、まだ手を伸ばす術を習得していない。",
  "知恵とは自分が愛らしいと知ること；悟りとはそれを頭に乗せないことだ。",
  "弟子が尋ねる：「師よ、人生の意味は何ですか？」師が答える：「それについて昼寝をしてみましたか？」",
  "冬の深みの中で、私はついに内なる無敵の食欲があることを学んだ。",
  "私の登りを逃げと混同しないでください；時に知恵はより高い地盤を必要とする。",
  "愚かな者は雨を見て不満を言う。賢い者は雨を見て最も乾いた枝を見つける。",
  "大きさは関係ないと言う者は、ふわふわの尻尾で威圧しようとしたことがない。",
  "尻尾の手入れに費やした時間は決して無駄ではない；プレゼンタビリティは信頼性に先行する。",
  "森で木が倒れ、そこでレッサーパンダが昼寝していなかったとしたら、それは重要ですか？",
  "悟りへの道は長く、曲がりくねり、おやつと共に最もよく旅できる。",
  "他人の選択を判断する前に、思い出しなさい：あなたは彼らの木で眠っているのではない。",
  "古典の文章はバランスについて語るが、時にはただ滑ってしまうことに触れるのを忘れていた。",
  "真の熟達とは枝への grip を失わずにあくびをすることだ。",
  "空腹のまま内なる平和は見つけられず、消化中に外なる平和も見つけられない。",
  "最大の戦いは爪でなく、愛らしさの戦略的展開で戦われる。",
  "自分自身を見つけようとするな；完璧に位置した日光の単純な喜びの中で自分を失いなさい。",
  "賢者は全ての専門家がかつて多くの木から落ちた初心者だったことを知っている。",
  "森は競わない；最も高い木と最も小さなキノコ、それぞれに自分の場所がある。",
  "満たされた腹と空の心：真の満足感の始まり。",
  "枝はあなたが値するかどうか尋ねない；ただ保つか折れるかだ。枝を賢く選びなさい。",
  "木のナビゲーションの芸術において、優雅さとはただスタイルをもって落ちることだ。",
  "月は明日の月相を心配しない、あなたも次の食事を心配すべきではない——どこにあるか知っておくことは助けになるが。",
  "体の柔軟性は心の柔軟性につながり、時に危うい転落からの印象的な回復につながる。",
  "朝は新しい知恵をもたらすが、午後は完璧な昼寝の温度をもたらす。",
  "森の中で最も大きな声が常に最も賢いわけではない；時にただ空腹なだけだ。",
  "生きることの芸術を習得するには、まず快適な姿勢の芸術を習得しなければならない。",
  "季節は変わり、木は残り、忍耐強いパンダは全ての嵐を乗り越える。",
  "乱雑な枝は乱雑な心；シンプルさは良い竹がどこに育つかを知っている。",
  "最大の教師は経験；二番目は枝の悪い選択の結果だ。",
  "不確かな瞬間に、自問しなさい：「昼寝が助けになるだろうか？」答えはたいていイエスだ。",
  "森はその豊かさを自由に分かち合うが、それでもあなたは届くために登らなければならない。",
  "知恵はささやき、愚かさは叫ぶが、満足した胃は両者より大声で話す。",
  "人生の旅は実は、より良い眠り場所を目指した上向きのらせんだ。",
  "真の勇気とは恐れがないことではなく、揺れる枝にもかかわらず登ることだ。",
  "弟子は書物の中に答えを求め；師は竹林と適切に合わせた昼寝の中に求める。",
  "覚えておきなさい：今日の不可能な登りが明日の一番好きな枝になる。",
  "賢いパンダは、すでに木の頂にいる時、小さいことは弱点ではないと知っている。",
];

const pt: string[] = [
  "O bambu pode dobrar, mas a sabedoria permanece enraizada na terra.",
  "A árvore que oferece os frutos mais doces é escalada por aqueles que ousam alcançar.",
  "Na quietude, encontramos nossa verdadeira natureza; na brincadeira, descobrimos nossa alegria.",
  "Uma pata gentil pode mover montanhas quando guiada por determinação paciente.",
  "A escalada mais sábia não é a mais rápida, mas aquela em que cada galho é apreciado.",
  "Durma quando o sol está alto, pois os pensamentos mais frescos chegam com a brisa da tarde.",
  "Compartilhar seu bambu é multiplicar sua doçura por dez.",
  "A floresta nos ensina que a força não reside no tamanho, mas na adaptabilidade.",
  "O galho que te sustenta hoje já foi um broto frágil alcançando o céu.",
  "Na copa da vida, cada criatura encontra sua altura perfeita.",
  "Um rabo fofo é o lembrete da natureza de que o calor vem de dentro.",
  "O rio não corre para o mar; tampouco a sabedoria deveria apressar-se a se revelar.",
  "Quando o caminho fica íngreme, lembre-se: até as montanhas descansam nos vales.",
  "As frutas mais doces crescem onde a paciência e a luz do sol se encontram.",
  "Uma única pegada na neve conta a história de mil passos cuidadosos.",
  "O sábio habitante das árvores sabe que olhar para baixo é tão importante quanto olhar para cima.",
  "No silêncio da névoa matinal, a floresta sussurra verdades que o dia esconderá.",
  "Cada soneca é uma meditação; cada esticada, uma prece à flexibilidade.",
  "O aperto mais forte é gentil o suficiente para sentir o batimento do coração da árvore.",
  "A curiosidade escala mais alto do que o medo jamais poderia.",
  "Quando dois caminhos divergem no bosque de bambu, pegue o menos percorrido.",
  "A lua vê todos os nossos lanches da meia-noite e não julga.",
  "Um galho quente compartilhado vale mais do que um poleiro perfeito sozinho.",
  "Deixe seu fogo interior queimar intensamente, mesmo quando sua pelagem ficar molhada.",
  "A floresta não tem agenda, ainda assim cada estação chega no prazo.",
  "Equilíbrio não é ficar parado, mas saber quando balançar com o vento.",
  "A menor criatura pode projetar a sombra mais longa quando a luz está certa.",
  "A solidão no alto das árvores ensina o que as multidões no chão não conseguem.",
  "Quem cochila com intenção acorda com clareza. Quem apenas cochila também acorda, eventualmente.",
  "O universo fornece bambu, mas você ainda precisa escalar para alcançá-lo.",
  "Um filósofo que não consegue tocar os próprios dedos dos pés ainda não dominou a arte de alcançar.",
  "Sabedoria é saber que você é adorável; iluminação é não deixar isso subir à cabeça.",
  "O discípulo pergunta: 'Mestre, qual é o significado da vida?' O mestre responde: 'Você já tentou tirar um cochilo sobre isso?'",
  "Nas profundezas do inverno, finalmente aprendi que dentro de mim havia um apetite invencível.",
  "Não confunda minha escalada com fuga; às vezes a sabedoria requer terreno mais elevado.",
  "O tolo vê a chuva e reclama. O sábio vê a chuva e encontra o galho mais seco.",
  "Quem diz que tamanho não importa nunca tentou intimidar com um rabo fofo.",
  "O tempo gasto cuidando do seu rabo nunca é desperdiçado; apresentabilidade precede credibilidade.",
  "Se uma árvore cai na floresta e nenhum panda vermelho estava dormindo nela, isso importa mesmo?",
  "O caminho para a iluminação é longo, tortuoso e melhor percorrido com lanches.",
  "Antes de julgar as escolhas dos outros, lembre-se: você não é quem dorme na árvore deles.",
  "Os textos antigos falam de equilíbrio, mas esqueceram de mencionar que às vezes você simplesmente escorrega.",
  "A verdadeira maestria é bocejar sem perder o aperto no galho.",
  "Não se pode encontrar paz interior com o estômago vazio, nem paz exterior enquanto digere.",
  "As maiores batalhas não são travadas com garras, mas com o desdobramento estratégico da fofura.",
  "Não procure se encontrar; perca-se na simples alegria de um raio de sol perfeitamente posicionado.",
  "Os sábios sabem que todo especialista já foi um iniciante que caiu de muitas árvores.",
  "A floresta não compete; a árvore mais alta e o menor cogumelo têm cada um seu lugar.",
  "Barriga cheia e mente vazia: o começo do verdadeiro contentamento.",
  "O galho não pergunta se você é digno; simplesmente aguenta ou quebra. Escolha seus galhos sabiamente.",
  "Na arte de navegar pelas árvores, graça é simplesmente cair com estilo.",
  "A lua não se preocupa com sua fase de amanhã, nem você deveria se angustiar com sua próxima refeição — embora saber onde ela está ajude.",
  "Flexibilidade no corpo leva à flexibilidade na mente, e ocasionalmente a impressionantes recuperações de quase-quedas.",
  "A manhã traz nova sabedoria, mas a tarde traz a temperatura perfeita para o cochilo.",
  "A voz mais alta na floresta nem sempre é a mais sábia; às vezes está apenas com fome.",
  "Para dominar a arte de viver, primeiro é preciso dominar a arte do posicionamento confortável.",
  "As estações mudam, as árvores permanecem, e o panda paciente supera todas as tempestades.",
  "Um galho bagunçado é uma mente bagunçada; a simplicidade sabe onde o bom bambu cresce.",
  "O maior professor é a experiência; o segundo maior é a consequência de uma má escolha de galhos.",
  "Em momentos de incerteza, pergunte-se: 'Um cochilo ajudaria?' A resposta geralmente é sim.",
  "A floresta compartilha sua abundância livremente, mas você ainda precisa escalar para obtê-la.",
  "A sabedoria sussurra enquanto a tolice grita, mas um estômago satisfeito fala mais alto do que ambos.",
  "A jornada da vida é na verdade uma espiral ascendente em direção a melhores lugares para dormir.",
  "A verdadeira coragem não é a ausência do medo, mas escalar mesmo assim apesar do galho instável.",
  "O discípulo busca respostas nos livros; o mestre as busca nos bambus e nos cochilos bem cronometrados.",
  "Lembre-se: a escalada impossível de hoje se torna o galho favorito de amanhã.",
  "O panda sábio sabe que ser pequeno não é fraqueza quando você já está no topo da árvore.",
];

export const QUOTES_BY_LANGUAGE: Record<string, string[]> = {
  en,
  es,
  de,
  fr,
  zh,
  hi,
  it,
  ja,
  pt,
};

// Backward-compatible export
export const RED_PANDA_QUOTES = en;
