const en: string[] = [
  "Bamboo may bend, but wisdom remains rooted in the earth.",
  "The tree that offers the sweetest fruit is climbed by those who dare to reach.",
  "In stillness, we find our true nature; in play, we discover our joy.",
  "A gentle paw can move mountains when guided by patient determination.",
  "The wisest climb is not the fastest, but the one where each branch is cherished.",
  "Sleep when the sun is high, for the coolest thoughts come with the evening breeze.",
  "To share your bamboo is to multiply its sweetness tenfold.",
  "The forest teaches us that strength lies not in size, but in adaptability.",
  "The branch that holds you today was once a fragile shoot reaching for the sky.",
  "In the canopy of life, every creature finds their perfect height.",
  "A fluffy tail is nature's reminder that warmth comes from within.",
  "The river does not rush to the sea; neither should wisdom hurry to reveal itself.",
  "When the path grows steep, remember: even mountains rest in valleys.",
  "The sweetest berries grow where patience and sunlight meet.",
  "A single paw print in snow tells the story of a thousand careful steps.",
  "The wise tree-dweller knows that looking down is as important as looking up.",
  "In the quiet of morning mist, the forest whispers truths the day will hide.",
  "Every nap is a meditation; every stretch, a prayer to flexibility.",
  "The strongest grip is gentle enough to feel the heartbeat of the tree.",
  "Curiosity climbs higher than fear ever could.",
  "When two paths diverge in the bamboo grove, take the one less trampled.",
  "The moon sees all our midnight snacks and judges not.",
  "A warm branch shared is worth more than a perfect perch alone.",
  "Let your inner fire burn bright, even when your fur gets wet.",
  "The forest has no schedule, yet every season arrives on time.",
  "Balance is not standing still, but knowing when to sway with the wind.",
  "The smallest creature can cast the longest shadow when the light is right.",
  "Solitude in the treetops teaches what crowds on the ground cannot.",
  "He who naps with intention awakens with clarity. He who just naps also awakens, eventually.",
  "The universe provides bamboo, but you must still climb to reach it.",
  "A philosopher who cannot touch their toes has not yet mastered the art of reaching.",
  "Wisdom is knowing you're adorable; enlightenment is not letting it go to your head.",
  "The student asks: 'Master, what is the meaning of life?' The master replies: 'Have you tried napping on it?'",
  "In the depths of winter, I finally learned that within me there lay an invincible appetite.",
  "Do not mistake my climbing for fleeing; sometimes wisdom requires higher ground.",
  "The fool sees rain and complains. The wise see rain and find the driest branch.",
  "Those who say size doesn't matter have never tried to intimidate with a fluffy tail.",
  "Time spent grooming your tail is never wasted; presentability precedes credibility.",
  "If a tree falls in the forest and no red panda was napping in it, does it even matter?",
  "The path to enlightenment is long, winding, and best traveled with snacks.",
  "Before you judge another's choices, remember: you're not the one sleeping in their tree.",
  "The ancient texts speak of balance, but they forgot to mention that sometimes you just slip.",
  "True mastery is yawning without losing your grip on the branch.",
  "One cannot find inner peace on an empty stomach, nor outer peace while digesting.",
  "The greatest battles are fought not with claws, but with the strategic deployment of cuteness.",
  "Seek not to find yourself, but to lose yourself in the simple joy of a perfectly positioned sunbeam.",
  "The wise know that every expert was once a beginner who fell out of many trees.",
  "The forest does not compete; the tallest tree and smallest mushroom each have their place.",
  "A full belly and an empty mind: the beginning of true contentment.",
  "The branch does not ask if you are worthy; it simply holds or breaks. Choose your branches wisely.",
  "In the art of tree navigation, grace is simply falling with style.",
  "The moon does not worry about tomorrow's phase, nor should you fret about your next meal—though knowing where it is helps.",
  "Flexibility in body leads to flexibility in mind, and occasionally to impressive recoveries from near-falls.",
  "Morning brings new wisdom, but afternoon brings the perfect napping temperature.",
  "The loudest voice in the forest is not always the wisest; sometimes it's just hungry.",
  "To master the art of living, one must first master the art of comfortable positioning.",
  "The seasons change, the trees remain, and the patient panda outlasts all storms.",
  "A cluttered branch is a cluttered mind; simplicity knows where the good bamboo grows.",
  "The greatest teacher is experience; the second greatest is the consequence of poor branch selection.",
  "In moments of uncertainty, ask yourself: 'Would a nap help?' The answer is usually yes.",
  "The forest shares its abundance freely, but you still have to climb for it.",
  "Wisdom whispers while foolishness shouts, but a satisfied stomach speaks louder than both.",
  "The journey of life is really an upward spiral toward better sleeping spots.",
  "True courage is not the absence of fear, but climbing anyway despite the wobbly branch.",
  "The student seeks answers in books; the master seeks answers in bamboo groves and well-timed naps.",
  "Remember: today's impossible climb becomes tomorrow's favorite branch.",
  "The wise panda knows that being small is not a weakness when you're already at the top of the tree.",
];

const es: string[] = [
  "El bambú puede doblarse, pero la sabiduría permanece arraigada en la tierra.",
  "El árbol que ofrece el fruto más dulce es escalado por quienes se atreven a alcanzarlo.",
  "En la quietud encontramos nuestra verdadera naturaleza; en el juego, descubrimos nuestra alegría.",
  "Una pata suave puede mover montañas cuando la guía la determinación paciente.",
  "La escalada más sabia no es la más rápida, sino aquella donde cada rama es apreciada.",
  "Duerme cuando el sol está alto, pues los pensamientos más frescos llegan con la brisa de la tarde.",
  "Compartir tu bambú es multiplicar su dulzura diez veces.",
  "El bosque nos enseña que la fuerza no reside en el tamaño, sino en la adaptabilidad.",
  "La rama que te sostiene hoy fue una vez un brote frágil que alcanzaba el cielo.",
  "En el dosel de la vida, cada criatura encuentra su altura perfecta.",
  "Una cola esponjosa es el recordatorio de la naturaleza de que el calor viene desde adentro.",
  "El río no corre al mar; tampoco debería la sabiduría apresurarse a revelarse.",
  "Cuando el camino se empina, recuerda: hasta las montañas descansan en los valles.",
  "Las bayas más dulces crecen donde se encuentran la paciencia y la luz del sol.",
  "Una sola huella de pata en la nieve cuenta la historia de mil pasos cuidadosos.",
  "El sabio habitante de los árboles sabe que mirar hacia abajo es tan importante como mirar hacia arriba.",
  "En el silencio de la neblina matutina, el bosque susurra verdades que el día ocultará.",
  "Cada siesta es una meditación; cada estiramiento, una oración a la flexibilidad.",
  "El agarre más fuerte es lo suficientemente suave para sentir el latido del árbol.",
  "La curiosidad escala más alto de lo que el miedo podría jamás hacerlo.",
  "Cuando dos caminos se bifurcan en el bambuzal, toma el menos pisoteado.",
  "La luna ve todos nuestros bocadillos de medianoche y no juzga.",
  "Una rama cálida compartida vale más que una percha perfecta en soledad.",
  "Deja que tu fuego interior brille con fuerza, incluso cuando tu pelaje se moje.",
  "El bosque no tiene horario, pero cada estación llega puntual.",
  "El equilibrio no es quedarse quieto, sino saber cuándo mecerse con el viento.",
  "La criatura más pequeña puede proyectar la sombra más larga cuando la luz es perfecta.",
  "La soledad en las copas de los árboles enseña lo que las multitudes en el suelo no pueden.",
  "Quien duerme con intención despierta con claridad. Quien simplemente duerme también despierta, eventualmente.",
  "El universo provee bambú, pero aún debes escalar para alcanzarlo.",
  "Un filósofo que no puede tocarse los dedos del pie aún no ha dominado el arte de alcanzar.",
  "La sabiduría es saber que eres adorable; la iluminación es no dejar que se te suba a la cabeza.",
  "El estudiante pregunta: '¿Maestro, cuál es el significado de la vida?' El maestro responde: '¿Has intentado dormir una siesta sobre eso?'",
  "En lo más profundo del invierno, finalmente aprendí que dentro de mí yacía un apetito invencible.",
  "No confundas mi escalada con huida; a veces la sabiduría requiere terreno más elevado.",
  "El necio ve la lluvia y se queja. El sabio ve la lluvia y encuentra la rama más seca.",
  "Quienes dicen que el tamaño no importa nunca han intentado intimidar con una cola esponjosa.",
  "El tiempo dedicado a acicalar tu cola nunca se desperdicia; la presentabilidad precede a la credibilidad.",
  "Si un árbol cae en el bosque y ningún panda rojo estaba durmiendo en él, ¿realmente importa?",
  "El camino a la iluminación es largo, sinuoso y mejor recorrido con bocadillos.",
  "Antes de juzgar las elecciones de otro, recuerda: tú no eres quien duerme en su árbol.",
  "Los textos antiguos hablan de equilibrio, pero olvidaron mencionar que a veces simplemente te resbalas.",
  "La verdadera maestría es bostezar sin perder el agarre en la rama.",
  "Uno no puede encontrar la paz interior con el estómago vacío, ni la paz exterior mientras digiere.",
  "Las grandes batallas no se libran con garras, sino con el despliegue estratégico de la ternura.",
  "No busques encontrarte a ti mismo; piérdete en la simple alegría de un rayo de sol perfectamente posicionado.",
  "Los sabios saben que todo experto fue una vez un principiante que cayó de muchos árboles.",
  "El bosque no compite; el árbol más alto y el hongo más pequeño cada uno tiene su lugar.",
  "Vientre lleno y mente vacía: el comienzo del verdadero contentamiento.",
  "La rama no pregunta si eres digno; simplemente sostiene o se rompe. Elige tus ramas sabiamente.",
  "En el arte de navegar árboles, la gracia es simplemente caer con estilo.",
  "La luna no se preocupa por la fase de mañana, ni tú deberías angustiarte por tu próxima comida, aunque saber dónde está ayuda.",
  "La flexibilidad del cuerpo conduce a la flexibilidad de la mente, y ocasionalmente a recuperaciones impresionantes de casi caídas.",
  "La mañana trae nueva sabiduría, pero la tarde trae la temperatura perfecta para la siesta.",
  "La voz más alta en el bosque no siempre es la más sabia; a veces simplemente tiene hambre.",
  "Para dominar el arte de vivir, primero hay que dominar el arte del posicionamiento cómodo.",
  "Las estaciones cambian, los árboles permanecen, y el panda paciente sobrevive a todas las tormentas.",
  "Una rama desordenada es una mente desordenada; la simplicidad sabe dónde crece el buen bambú.",
  "El mayor maestro es la experiencia; el segundo mayor es la consecuencia de una mala selección de ramas.",
  "En momentos de incertidumbre, pregúntate: '¿Ayudaría una siesta?' La respuesta generalmente es sí.",
  "El bosque comparte su abundancia libremente, pero aún tienes que escalar para conseguirla.",
  "La sabiduría susurra mientras la necedad grita, pero un estómago satisfecho habla más fuerte que ambos.",
  "El viaje de la vida es realmente una espiral ascendente hacia mejores lugares para dormir.",
  "El verdadero coraje no es la ausencia del miedo, sino escalar de todas formas a pesar de la rama tambaleante.",
  "El estudiante busca respuestas en los libros; el maestro las busca en los bambuzales y las siestas bien programadas.",
  "Recuerda: la escalada imposible de hoy se convierte en la rama favorita de mañana.",
  "El panda sabio sabe que ser pequeño no es una debilidad cuando ya estás en la cima del árbol.",
];

const de: string[] = [
  "Bambus mag sich biegen, aber Weisheit bleibt in der Erde verwurzelt.",
  "Den Baum mit den süßesten Früchten erklimmen jene, die es wagen zu greifen.",
  "In der Stille finden wir unser wahres Wesen; im Spiel entdecken wir unsere Freude.",
  "Eine sanfte Pfote kann Berge versetzen, wenn sie von geduldiger Entschlossenheit geleitet wird.",
  "Die weiseste Klettertour ist nicht die schnellste, sondern jene, bei der jeder Ast gewürdigt wird.",
  "Schlafe wenn die Sonne hoch steht, denn die kühlsten Gedanken kommen mit dem Abendwind.",
  "Seinen Bambus zu teilen bedeutet, seine Süße zehnfach zu vervielfachen.",
  "Der Wald lehrt uns, dass Stärke nicht in der Größe liegt, sondern in der Anpassungsfähigkeit.",
  "Der Ast, der dich heute hält, war einst ein zarter Trieb, der nach dem Himmel strebte.",
  "Im Blätterdach des Lebens findet jedes Wesen seine perfekte Höhe.",
  "Ein flauschiger Schwanz ist die Erinnerung der Natur, dass Wärme von innen kommt.",
  "Der Fluss eilt nicht zum Meer; auch die Weisheit sollte es nicht eilig haben, sich zu zeigen.",
  "Wenn der Weg steiler wird, erinnere dich: Sogar Berge ruhen in Tälern.",
  "Die süßesten Beeren wachsen dort, wo Geduld und Sonnenlicht sich begegnen.",
  "Ein einzelner Pfotentapfen im Schnee erzählt die Geschichte von tausend behutsamen Schritten.",
  "Der weise Baumklettertier weiß, dass nach unten zu schauen genauso wichtig ist wie nach oben.",
  "In der Stille des Morgennebels flüstert der Wald Wahrheiten, die der Tag verbergen wird.",
  "Jedes Nickerchen ist eine Meditation; jedes Strecken ein Gebet an die Flexibilität.",
  "Der stärkste Griff ist sanft genug, um den Herzschlag des Baumes zu spüren.",
  "Neugier klettert höher, als die Angst es je könnte.",
  "Wenn sich zwei Pfade im Bambuswäldchen teilen, nimm den weniger ausgetretenen.",
  "Der Mond sieht all unsere mitternächtlichen Snacks und urteilt nicht.",
  "Ein geteilter warmer Ast ist mehr wert als ein perfekter Sitzplatz allein.",
  "Lass dein inneres Feuer hell leuchten, auch wenn dein Fell nass wird.",
  "Der Wald hat keinen Zeitplan, und doch kommt jede Jahreszeit pünktlich.",
  "Gleichgewicht ist nicht Stillstand, sondern zu wissen, wann man sich im Wind wiegt.",
  "Das kleinste Wesen kann den längsten Schatten werfen, wenn das Licht stimmt.",
  "Einsamkeit in den Baumwipfeln lehrt, was Menschenmassen am Boden nicht können.",
  "Wer mit Absicht schläft, erwacht mit Klarheit. Wer einfach schläft, erwacht auch, irgendwann.",
  "Das Universum stellt Bambus bereit, aber du musst noch klettern, um ihn zu erreichen.",
  "Ein Philosoph, der seine Zehen nicht berühren kann, hat die Kunst des Greifens noch nicht gemeistert.",
  "Weisheit ist zu wissen, dass du entzückend bist; Erleuchtung ist, es nicht zu Kopf steigen zu lassen.",
  "Der Schüler fragt: 'Meister, was ist der Sinn des Lebens?' Der Meister antwortet: 'Hast du versucht, darüber ein Nickerchen zu halten?'",
  "In der Tiefe des Winters erkannte ich schließlich, dass in mir ein unbesiegbarer Appetit schlummerte.",
  "Verwechsle mein Klettern nicht mit Flucht; manchmal erfordert Weisheit höheres Terrain.",
  "Der Narr sieht Regen und klagt. Der Weise sieht Regen und findet den trockensten Ast.",
  "Wer sagt, Größe spiele keine Rolle, hat noch nie versucht, mit einem flauschigen Schwanz einzuschüchtern.",
  "Zeit, die man damit verbringt, seinen Schwanz zu pflegen, ist nie verschwendet; Präsentabilität geht der Glaubwürdigkeit voraus.",
  "Wenn ein Baum im Wald fällt und kein roter Panda darin geschlafen hat, spielt es dann überhaupt eine Rolle?",
  "Der Weg zur Erleuchtung ist lang, kurvenreich und lässt sich am besten mit Snacks bereisen.",
  "Bevor du die Entscheidungen anderer bewertest, erinnere dich: Du schläfst nicht in ihrem Baum.",
  "Die alten Texte sprechen von Gleichgewicht, vergaßen aber zu erwähnen, dass man manchmal einfach ausrutscht.",
  "Wahre Meisterschaft ist es, zu gähnen ohne den Griff am Ast zu verlieren.",
  "Man kann keinen inneren Frieden auf leerem Magen finden, noch äußeren Frieden beim Verdauen.",
  "Die größten Kämpfe werden nicht mit Krallen geführt, sondern mit dem strategischen Einsatz von Niedlichkeit.",
  "Suche nicht danach, dich selbst zu finden; verliere dich in der schlichten Freude eines perfekt platzierten Sonnenstrahls.",
  "Die Weisen wissen, dass jeder Experte einst ein Anfänger war, der von vielen Bäumen fiel.",
  "Der Wald konkurriert nicht; der höchste Baum und der kleinste Pilz haben ihren Platz.",
  "Ein voller Bauch und ein leerer Geist: der Beginn wahren Zufriedenseins.",
  "Der Ast fragt nicht, ob du es verdient hast; er hält oder bricht einfach. Wähle deine Äste weise.",
  "In der Kunst der Baumnavigation ist Anmut einfach das Fallen mit Stil.",
  "Der Mond sorgt sich nicht um die Phase von morgen; auch du solltest dich nicht um deine nächste Mahlzeit sorgen – obwohl zu wissen, wo sie ist, hilft.",
  "Körperliche Flexibilität führt zu geistiger Flexibilität und gelegentlich zu beeindruckenden Erholungen nach Beinahe-Stürzen.",
  "Der Morgen bringt neue Weisheit, aber der Nachmittag bringt die perfekte Nickerchen-Temperatur.",
  "Die lauteste Stimme im Wald ist nicht immer die weiseste; manchmal hat sie einfach Hunger.",
  "Um die Kunst des Lebens zu meistern, muss man zunächst die Kunst der bequemen Positionierung meistern.",
  "Die Jahreszeiten wechseln, die Bäume bleiben, und der geduldige Panda überdauert alle Stürme.",
  "Ein unordentlicher Ast ist ein unordentlicher Geist; Einfachheit weiß, wo der gute Bambus wächst.",
  "Der größte Lehrer ist die Erfahrung; der zweitgrößte sind die Folgen schlechter Astauswahl.",
  "Frage dich in Momenten der Ungewissheit: 'Würde ein Nickerchen helfen?' Die Antwort ist meistens ja.",
  "Der Wald teilt seinen Reichtum frei, aber du musst noch klettern, um ihn zu bekommen.",
  "Weisheit flüstert, während Dummheit schreit, aber ein zufriedener Magen spricht lauter als beide.",
  "Die Lebensreise ist eigentlich eine aufwärts gerichtete Spirale zu besseren Schlafplätzen.",
  "Wahre Tapferkeit ist nicht die Abwesenheit von Angst, sondern trotzdem zu klettern, trotz des wackelnden Astes.",
  "Der Schüler sucht Antworten in Büchern; der Meister sucht sie in Bambuswäldern und gut getimten Nickerchen.",
  "Denke daran: Die unmögliche Klettertour von heute wird der Lieblingsast von morgen.",
  "Der weise Panda weiß, dass klein zu sein keine Schwäche ist, wenn man bereits an der Spitze des Baumes ist.",
];

const fr: string[] = [
  "Le bambou peut plier, mais la sagesse reste enracinée dans la terre.",
  "L'arbre qui offre les fruits les plus doux est gravi par ceux qui osent s'étirer pour les atteindre.",
  "Dans l'immobilité, nous trouvons notre vraie nature ; dans le jeu, nous découvrons notre joie.",
  "Une douce patte peut déplacer des montagnes guidée par une détermination patiente.",
  "L'ascension la plus sage n'est pas la plus rapide, mais celle où chaque branche est chérie.",
  "Dors quand le soleil est haut, car les pensées les plus fraîches viennent avec la brise du soir.",
  "Partager son bambou, c'est multiplier sa douceur par dix.",
  "La forêt nous enseigne que la force ne réside pas dans la taille, mais dans l'adaptabilité.",
  "La branche qui te soutient aujourd'hui était autrefois un fragile bourgeon aspirant vers le ciel.",
  "Dans la canopée de la vie, chaque créature trouve sa hauteur parfaite.",
  "Une queue touffue est le rappel de la nature que la chaleur vient de l'intérieur.",
  "Le fleuve ne se précipite pas vers la mer ; la sagesse non plus ne devrait pas se hâter de se révéler.",
  "Quand le chemin devient escarpé, souviens-toi : même les montagnes se reposent dans les vallées.",
  "Les baies les plus douces poussent là où la patience et le soleil se rencontrent.",
  "Une seule empreinte de patte dans la neige raconte l'histoire de mille pas prudents.",
  "Le sage grimpeur d'arbres sait que regarder vers le bas est aussi important que regarder vers le haut.",
  "Dans le calme de la brume matinale, la forêt chuchote des vérités que le jour cachera.",
  "Chaque sieste est une méditation ; chaque étirement, une prière à la souplesse.",
  "La prise la plus solide est assez douce pour sentir le battement de cœur de l'arbre.",
  "La curiosité grimpe plus haut que la peur ne le pourrait jamais.",
  "Quand deux chemins divergent dans la bambouseraie, prends celui le moins piétiné.",
  "La lune voit tous nos encas de minuit et ne juge pas.",
  "Une branche chaude partagée vaut plus qu'un perchoir parfait en solitaire.",
  "Laisse ton feu intérieur briller intensément, même quand ton pelage est mouillé.",
  "La forêt n'a pas d'horaire, pourtant chaque saison arrive à temps.",
  "L'équilibre n'est pas l'immobilité, mais savoir quand se balancer avec le vent.",
  "La plus petite créature peut projeter la plus longue ombre quand la lumière est juste.",
  "La solitude dans les cimes enseigne ce que les foules au sol ne peuvent pas.",
  "Celui qui fait une sieste avec intention s'éveille avec clarté. Celui qui fait simplement une sieste s'éveille aussi, éventuellement.",
  "L'univers fournit le bambou, mais tu dois quand même grimper pour l'atteindre.",
  "Un philosophe qui ne peut pas toucher ses orteils n'a pas encore maîtrisé l'art d'atteindre.",
  "La sagesse c'est de savoir qu'on est adorable ; l'illumination c'est ne pas la laisser monter à la tête.",
  "L'élève demande : 'Maître, quel est le sens de la vie ?' Le maître répond : 'As-tu essayé de faire une sieste dessus ?'",
  "Dans les profondeurs de l'hiver, j'ai finalement appris qu'en moi sommeillait un appétit invincible.",
  "Ne confonds pas mon escalade avec une fuite ; parfois la sagesse nécessite un terrain plus élevé.",
  "Le fou voit la pluie et se plaint. Le sage voit la pluie et trouve la branche la plus sèche.",
  "Ceux qui disent que la taille n'a pas d'importance n'ont jamais essayé d'intimider avec une queue touffue.",
  "Le temps consacré à se lisser la queue n'est jamais perdu ; la présentation précède la crédibilité.",
  "Si un arbre tombe dans la forêt et qu'aucun panda roux n'y dormait, est-ce que ça compte vraiment ?",
  "Le chemin vers l'illumination est long, sinueux, et mieux parcouru avec des en-cas.",
  "Avant de juger les choix d'autrui, souviens-toi : tu n'es pas celui qui dort dans son arbre.",
  "Les anciens textes parlent d'équilibre, mais ils ont oublié de mentionner qu'on glisse parfois.",
  "La vraie maîtrise, c'est bâiller sans perdre sa prise sur la branche.",
  "On ne peut pas trouver la paix intérieure le ventre vide, ni la paix extérieure en digérant.",
  "Les plus grandes batailles ne se mènent pas avec des griffes, mais avec le déploiement stratégique de la mignonnerie.",
  "Ne cherche pas à te trouver ; perds-toi dans la simple joie d'un rayon de soleil parfaitement positionné.",
  "Les sages savent que chaque expert était autrefois un débutant qui est tombé de nombreux arbres.",
  "La forêt ne rivalise pas ; le plus grand arbre et le plus petit champignon ont chacun leur place.",
  "Un ventre plein et un esprit vide : le début du vrai contentement.",
  "La branche ne demande pas si tu en es digne ; elle tient ou cède simplement. Choisis tes branches sagement.",
  "Dans l'art de naviguer les arbres, la grâce c'est simplement tomber avec style.",
  "La lune ne s'inquiète pas de sa phase demain, et tu ne devrais pas t'inquiéter de ton prochain repas — bien que savoir où il se trouve aide.",
  "La flexibilité du corps mène à la flexibilité de l'esprit, et parfois à de remarquables récupérations après des quasi-chutes.",
  "Le matin apporte de nouvelles sagesses, mais l'après-midi apporte la température parfaite pour la sieste.",
  "La voix la plus forte dans la forêt n'est pas toujours la plus sage ; parfois elle a juste faim.",
  "Pour maîtriser l'art de vivre, il faut d'abord maîtriser l'art du positionnement confortable.",
  "Les saisons changent, les arbres demeurent, et le panda patient survit à toutes les tempêtes.",
  "Une branche encombrée est un esprit encombré ; la simplicité sait où pousse le bon bambou.",
  "Le plus grand professeur est l'expérience ; le deuxième est la conséquence d'un mauvais choix de branche.",
  "Dans les moments d'incertitude, demande-toi : 'Une sieste aiderait-elle ?' La réponse est généralement oui.",
  "La forêt partage son abondance librement, mais tu dois quand même grimper pour l'obtenir.",
  "La sagesse chuchote tandis que la sottise crie, mais un estomac satisfait parle plus fort que les deux.",
  "Le voyage de la vie est en réalité une spirale ascendante vers de meilleurs spots pour dormir.",
  "Le vrai courage n'est pas l'absence de peur, mais grimper quand même malgré la branche branlante.",
  "L'élève cherche des réponses dans les livres ; le maître les cherche dans les bambouseraies et les siestes bien placées.",
  "Souviens-toi : l'escalade impossible d'aujourd'hui devient la branche préférée de demain.",
  "Le panda sage sait qu'être petit n'est pas une faiblesse quand on est déjà au sommet de l'arbre.",
];

export const QUOTES_BY_LANGUAGE: Record<string, string[]> = { en, es, de, fr };

// Backward-compatible export
export const RED_PANDA_QUOTES = en;
