export const RED_PANDA_QUOTES = [
  "Bamboo may bend, but wisdom remains rooted in the earth.",
  "The tree that offers the sweetest fruit is climbed by those who dare to reach.",
  "In stillness, we find our true nature; in play, we discover our joy.",
  "A gentle paw can move mountains when guided by patient determination.",
  "The wisest climb is not the fastest, but the one where each branch is cherished.",
  "Sleep when the sun is high, for the coolest thoughts come with the evening breeze.",
  "To share your bamboo is to multiply its sweetness tenfold.",
  "The forest teaches us that strength lies not in size, but in adaptability.",
  "The branch that holds you today was once a fragile shoot reaching for the sky.",
  "In the canopy of life, every creature finds their perfect height.",
  "A fluffy tail is nature's reminder that warmth comes from within.",
  "The river does not rush to the sea; neither should wisdom hurry to reveal itself.",
  "When the path grows steep, remember: even mountains rest in valleys.",
  "The sweetest berries grow where patience and sunlight meet.",
  "A single paw print in snow tells the story of a thousand careful steps.",
  "The wise tree-dweller knows that looking down is as important as looking up.",
  "In the quiet of morning mist, the forest whispers truths the day will hide.",
  "Every nap is a meditation; every stretch, a prayer to flexibility.",
  "The strongest grip is gentle enough to feel the heartbeat of the tree.",
  "Curiosity climbs higher than fear ever could.",
  "When two paths diverge in the bamboo grove, take the one less trampled.",
  "The moon sees all our midnight snacks and judges not.",
  "A warm branch shared is worth more than a perfect perch alone.",
  "Let your inner fire burn bright, even when your fur gets wet.",
  "The forest has no schedule, yet every season arrives on time.",
  "Balance is not standing still, but knowing when to sway with the wind.",
  "The smallest creature can cast the longest shadow when the light is right.",
  "Solitude in the treetops teaches what crowds on the ground cannot.",
  "He who naps with intention awakens with clarity. He who just naps also awakens, eventually.",
  "The universe provides bamboo, but you must still climb to reach it.",
  "A philosopher who cannot touch their toes has not yet mastered the art of reaching.",
  "Wisdom is knowing you're adorable; enlightenment is not letting it go to your head.",
  "The student asks: 'Master, what is the meaning of life?' The master replies: 'Have you tried napping on it?'",
  "In the depths of winter, I finally learned that within me there lay an invincible appetite.",
  "Do not mistake my climbing for fleeing; sometimes wisdom requires higher ground.",
  "The fool sees rain and complains. The wise see rain and find the driest branch.",
  "Those who say size doesn't matter have never tried to intimidate with a fluffy tail.",
  "Time spent grooming your tail is never wasted; presentability precedes credibility.",
  "If a tree falls in the forest and no red panda was napping in it, does it even matter?",
  "The path to enlightenment is long, winding, and best traveled with snacks.",
  "Before you judge another's choices, remember: you're not the one sleeping in their tree.",
  "The ancient texts speak of balance, but they forgot to mention that sometimes you just slip.",
  "True mastery is yawning without losing your grip on the branch.",
  "One cannot find inner peace on an empty stomach, nor outer peace while digesting.",
  "The greatest battles are fought not with claws, but with the strategic deployment of cuteness.",
  "Seek not to find yourself, but to lose yourself in the simple joy of a perfectly positioned sunbeam.",
  "The wise know that every expert was once a beginner who fell out of many trees.",
  "The forest does not compete; the tallest tree and smallest mushroom each have their place.",
  "A full belly and an empty mind: the beginning of true contentment.",
  "The branch does not ask if you are worthy; it simply holds or breaks. Choose your branches wisely.",
  "In the art of tree navigation, grace is simply falling with style.",
  "The moon does not worry about tomorrow's phase, nor should you fret about your next meal—though knowing where it is helps.",
  "Flexibility in body leads to flexibility in mind, and occasionally to impressive recoveries from near-falls.",
  "Morning brings new wisdom, but afternoon brings the perfect napping temperature.",
  "The loudest voice in the forest is not always the wisest; sometimes it's just hungry.",
  "To master the art of living, one must first master the art of comfortable positioning.",
  "The seasons change, the trees remain, and the patient panda outlasts all storms.",
  "A cluttered branch is a cluttered mind; simplicity knows where the good bamboo grows.",
  "The greatest teacher is experience; the second greatest is the consequence of poor branch selection.",
  "In moments of uncertainty, ask yourself: 'Would a nap help?' The answer is usually yes.",
  "The forest shares its abundance freely, but you still have to climb for it.",
  "Wisdom whispers while foolishness shouts, but a satisfied stomach speaks louder than both.",
  "The journey of life is really an upward spiral toward better sleeping spots.",
  "True courage is not the absence of fear, but climbing anyway despite the wobbly branch.",
  "The student seeks answers in books; the master seeks answers in bamboo groves and well-timed naps.",
  "Remember: today's impossible climb becomes tomorrow's favorite branch.",
  "The wise panda knows that being small is not a weakness when you're already at the top of the tree.",
];
