import { Dimensions, Platform, StyleSheet } from "react-native";
import { colors } from "@/constants/colors";
import { rs } from "@/core/theme/responsive";

const { width: SCREEN_WIDTH } = Dimensions.get("window");

export const onboardingStyles = StyleSheet.create({
  // ─── Welcome Screen (Screen 1) ────────────────────────────
  welcomeContainer: {
    flex: 1,
    backgroundColor: colors.brandAccent,
  },
  welcomeTopDecoration: {
    position: "absolute",
    top: -60,
    right: -40,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  welcomeBottomDecoration: {
    position: "absolute",
    bottom: -80,
    left: -60,
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  welcomeContent: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: rs(32),
    paddingVertical: rs(40),
    gap: rs(6),
  },
  welcomeImageWrapper: {
    width: rs(180),
    height: rs(180),
    borderRadius: rs(90),
    overflow: "hidden",
    marginBottom: rs(20),
    borderWidth: 4,
    borderColor: "rgba(255,255,255,0.5)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 8,
  },
  welcomePandaImage: {
    width: "100%",
    height: "100%",
  },
  welcomeTitle: {
    fontSize: rs(34),
    fontWeight: "800",
    color: "#ffffff",
    textAlign: "center",
    letterSpacing: -0.5,
  },
  welcomeSubtitle: {
    fontSize: rs(17),
    color: "rgba(255,255,255,0.85)",
    textAlign: "center",
    fontStyle: "italic",
    marginTop: 2,
  },
  welcomeDivider: {
    width: 40,
    height: 2,
    backgroundColor: "rgba(255,255,255,0.3)",
    borderRadius: 1,
    marginVertical: rs(14),
  },
  welcomeDescription: {
    fontSize: rs(15),
    color: "rgba(255,255,255,0.75)",
    textAlign: "center",
    lineHeight: rs(23),
    paddingHorizontal: rs(16),
    maxWidth: rs(320),
  },
  getStartedButton: {
    backgroundColor: "#ffffff",
    paddingVertical: rs(17),
    paddingHorizontal: rs(48),
    borderRadius: 30,
    marginTop: rs(28),
    shadowColor: "rgba(0,0,0,0.3)",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 6,
    minWidth: rs(220),
    alignItems: "center",
  },
  getStartedButtonText: {
    color: colors.brandDark,
    fontSize: rs(17),
    fontWeight: "700",
    letterSpacing: 0.3,
  },

  // ─── Shared layout for screens 2-5 ────────────────────────
  screenContainer: {
    flex: 1,
    backgroundColor: colors.brandLight,
  },
  screenContent: {
    flex: 1,
    paddingHorizontal: rs(28),
    paddingBottom: rs(16),
  },
  headerBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: Platform.select({ web: 24, default: 58 }),
    paddingHorizontal: rs(20),
    paddingBottom: 8,
  },
  headerBackButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.earthSand,
    justifyContent: "center",
    alignItems: "center",
  },
  headerBackText: {
    fontSize: 22,
    color: colors.brandDark,
    marginTop: -2,
  },
  headerTitle: {
    fontSize: rs(16),
    fontWeight: "600",
    color: colors.brandPrimary,
    letterSpacing: 0.3,
  },
  headerSkipButton: {
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: colors.earthSand,
  },
  headerSkipText: {
    fontSize: rs(14),
    fontWeight: "500",
    color: colors.brandPrimary,
  },
  headerSpacer: {
    width: 40,
  },

  // ─── Progress dots ─────────────────────────────────────────
  progressContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    paddingVertical: 12,
  },
  progressDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.earthSand,
  },
  progressDotActive: {
    width: 24,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.brandAccent,
  },

  // ─── Hagu image (smaller, for screens 2-4) ────────────────
  smallPandaWrapper: {
    width: rs(90),
    height: rs(90),
    borderRadius: rs(45),
    overflow: "hidden",
    alignSelf: "center",
    marginTop: rs(8),
    marginBottom: rs(20),
    borderWidth: 3,
    borderColor: colors.earthSand,
    shadowColor: colors.brandPrimary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 4,
  },
  smallPandaImage: {
    width: "100%",
    height: "100%",
  },

  // ─── Headings & subtitles ─────────────────────────────────
  heading: {
    fontSize: rs(28),
    fontWeight: "800",
    color: colors.brandDark,
    textAlign: "center",
    marginBottom: rs(6),
    letterSpacing: -0.3,
  },
  subtitle: {
    fontSize: rs(15),
    color: colors.brandPrimary,
    textAlign: "center",
    marginBottom: rs(28),
    lineHeight: rs(21),
  },

  // ─── Name screen input ────────────────────────────────────
  textInputWrapper: {
    marginHorizontal: 4,
  },
  textInputLabel: {
    fontSize: rs(13),
    fontWeight: "500",
    color: colors.brandPrimary,
    marginBottom: 8,
    marginLeft: 4,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  textInput: {
    backgroundColor: "#ffffff",
    borderWidth: 1.5,
    borderColor: colors.earthSand,
    borderRadius: 16,
    paddingVertical: rs(16),
    paddingHorizontal: rs(20),
    fontSize: rs(17),
    color: colors.brandDark,
  },
  textInputFocused: {
    borderColor: colors.brandAccent,
    shadowColor: colors.brandAccent,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 2,
  },

  // ─── Categories chip grid ─────────────────────────────────
  chipGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: rs(10),
    paddingHorizontal: 4,
  },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: rs(11),
    paddingHorizontal: rs(18),
    borderRadius: 22,
    backgroundColor: "#ffffff",
    borderWidth: 1.5,
    borderColor: colors.earthSand,
    gap: 6,
  },
  chipSelected: {
    backgroundColor: colors.brandSecondary,
    borderColor: colors.brandSecondary,
  },
  chipText: {
    fontSize: rs(15),
    color: colors.brandDark,
    fontWeight: "500",
  },
  chipTextSelected: {
    color: "#ffffff",
    fontWeight: "600",
  },
  chipCheckmark: {
    fontSize: rs(13),
    color: "#ffffff",
    fontWeight: "700",
  },
  chipCount: {
    textAlign: "center",
    fontSize: rs(13),
    color: colors.brandPrimary,
    marginTop: rs(16),
  },

  // ─── Notifications screen ─────────────────────────────────
  notificationCard: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: rs(18),
    marginHorizontal: 4,
    marginBottom: rs(28),
    borderWidth: 1,
    borderColor: colors.earthSand,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  notificationCardLabel: {
    fontSize: rs(11),
    fontWeight: "600",
    color: colors.brandPrimary,
    letterSpacing: 0.8,
    textTransform: "uppercase",
    marginBottom: rs(12),
  },
  notificationPreview: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    backgroundColor: colors.brandLight,
    borderRadius: 14,
    padding: rs(14),
  },
  notificationIcon: {
    width: rs(42),
    height: rs(42),
    borderRadius: 12,
    backgroundColor: colors.brandAccent,
    justifyContent: "center",
    alignItems: "center",
  },
  notificationIconText: {
    fontSize: rs(20),
  },
  notificationTextGroup: {
    flex: 1,
  },
  notificationPreviewTitle: {
    fontSize: rs(14),
    fontWeight: "700",
    color: colors.brandDark,
  },
  notificationPreviewBody: {
    fontSize: rs(13),
    color: colors.brandPrimary,
    marginTop: 2,
    fontStyle: "italic",
  },
  notificationPreviewTime: {
    fontSize: rs(11),
    color: colors.brandMuted,
    fontWeight: "500",
  },
  frequencySectionLabel: {
    fontSize: rs(13),
    fontWeight: "600",
    color: colors.brandDark,
    textAlign: "center",
    marginBottom: rs(12),
    letterSpacing: 0.2,
  },
  frequencyRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: rs(24),
    marginBottom: rs(24),
  },
  frequencyButton: {
    width: rs(44),
    height: rs(44),
    borderRadius: rs(22),
    backgroundColor: "#ffffff",
    borderWidth: 1.5,
    borderColor: colors.earthSand,
    justifyContent: "center",
    alignItems: "center",
  },
  frequencyButtonText: {
    fontSize: rs(22),
    color: colors.brandDark,
    fontWeight: "500",
  },
  frequencyValue: {
    fontSize: rs(32),
    fontWeight: "800",
    color: colors.brandDark,
    minWidth: rs(56),
    textAlign: "center",
    letterSpacing: -0.5,
  },
  frequencyUnit: {
    fontSize: rs(16),
    fontWeight: "400",
    color: colors.brandPrimary,
  },
  timeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: rs(12),
    marginBottom: rs(20),
  },
  timeBlock: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.earthSand,
    paddingVertical: rs(14),
    paddingHorizontal: rs(12),
  },
  timeLabel: {
    fontSize: rs(11),
    fontWeight: "600",
    color: colors.brandPrimary,
    marginBottom: 6,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  timeValue: {
    fontSize: rs(17),
    fontWeight: "700",
    color: colors.brandDark,
  },
  summaryText: {
    fontSize: rs(14),
    color: colors.brandPrimary,
    textAlign: "center",
    lineHeight: rs(21),
    fontStyle: "italic",
  },

  // ─── Bottom button (shared for screens 2-5) ───────────────
  bottomButtonContainer: {
    paddingHorizontal: rs(28),
    paddingBottom: Platform.select({ web: 28, default: 44 }),
    paddingTop: 12,
  },
  nextButton: {
    backgroundColor: colors.brandDark,
    paddingVertical: rs(17),
    borderRadius: 30,
    alignItems: "center",
    shadowColor: colors.brandDark,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  nextButtonDisabled: {
    backgroundColor: colors.earthSand,
    shadowOpacity: 0,
    elevation: 0,
  },
  nextButtonText: {
    color: "#ffffff",
    fontSize: rs(17),
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  nextButtonTextDisabled: {
    color: colors.brandPrimary,
  },

  // ─── Welcome back screen (Screen 5) ───────────────────────
  welcomeBackContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.brandLight,
    padding: rs(32),
  },
  welcomeBackDecoration: {
    position: "absolute",
    top: "30%",
    width: SCREEN_WIDTH * 0.7,
    height: SCREEN_WIDTH * 0.7,
    borderRadius: SCREEN_WIDTH * 0.35,
    backgroundColor: colors.brandAccent,
    opacity: 0.06,
  },
  welcomeBackImageWrapper: {
    width: rs(120),
    height: rs(120),
    borderRadius: rs(60),
    overflow: "hidden",
    marginBottom: rs(28),
    borderWidth: 3,
    borderColor: colors.earthSand,
    shadowColor: colors.brandPrimary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 6,
  },
  welcomeBackPandaImage: {
    width: "100%",
    height: "100%",
  },
  welcomeBackTitle: {
    fontSize: rs(40),
    fontWeight: "800",
    color: colors.brandDark,
    textAlign: "center",
    marginBottom: rs(8),
    letterSpacing: -0.5,
  },
  welcomeBackSubtitle: {
    fontSize: rs(17),
    color: colors.brandPrimary,
    textAlign: "center",
    fontStyle: "italic",
  },
  welcomeBackDots: {
    flexDirection: "row",
    gap: 6,
    marginTop: rs(24),
  },
  welcomeBackDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.brandAccent,
    opacity: 0.4,
  },
});
