import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#6B3E3E',
    padding: 20,
    gap: 20,
  },
  pandaImage: {
    width: 150,
    height: 150,
    borderRadius: 75,
    borderWidth: 3,
    borderColor: '#FFF5F0',
  },
  quoteContainer: {
    backgroundColor: '#FFF5F0',
    borderRadius: 16,
    padding: 30,
    marginBottom: 40,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
    maxWidth: 400,
  },
  quoteText: {
    fontSize: 24,
    lineHeight: 36,
    color: '#2D2D2D',
    textAlign: 'center',
    fontStyle: 'italic',
    marginBottom: 16,
  },
  author: {
    fontSize: 16,
    color: '#6B3E3E',
    textAlign: 'right',
  },
  buttonContainer: {
    gap: 12,
    alignItems: 'center',
  },
  secondaryButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
  },
  secondaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    textAlign: 'center',
  },
  completionContainer: {
    gap: 20,
    alignItems: 'center',
  },
  closingMessage: {
    fontSize: 16,
    color: '#FFFFFF',
    fontStyle: 'italic',
    textAlign: 'center',
  },
  intentionContainer: {
    paddingHorizontal: 40,
    gap: 12,
  },
  intentionText: {
    fontSize: 20,
    lineHeight: 32,
    color: '#FFFFFF',
    textAlign: 'center',
  },
  primaryButton: {
    backgroundColor: '#FFF5F0',
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 24,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
    minWidth: 200,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: '#6B3E3E',
    fontSize: 18,
    fontWeight: '600',
  },
});
