import { StyleSheet, Dimensions } from 'react-native';
import { colors } from '@/constants/colors';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const onboardingStyles = StyleSheet.create({
  // ─── Welcome Screen (Screen 1) ────────────────────────────
  welcomeContainer: {
    flex: 1,
    backgroundColor: colors.brandAccent,
  },
  welcomeTopDecoration: {
    position: 'absolute',
    top: -60,
    right: -40,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  welcomeBottomDecoration: {
    position: 'absolute',
    bottom: -80,
    left: -60,
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  welcomeContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
    gap: 6,
  },
  welcomeImageWrapper: {
    width: 180,
    height: 180,
    borderRadius: 90,
    overflow: 'hidden',
    marginBottom: 20,
    borderWidth: 4,
    borderColor: 'rgba(255,255,255,0.5)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 8,
  },
  welcomePandaImage: {
    width: '100%',
    height: '100%',
  },
  welcomeTitle: {
    fontSize: 34,
    fontWeight: '800',
    color: '#ffffff',
    textAlign: 'center',
    letterSpacing: -0.5,
  },
  welcomeSubtitle: {
    fontSize: 17,
    color: 'rgba(255,255,255,0.85)',
    textAlign: 'center',
    fontStyle: 'italic',
    marginTop: 2,
  },
  welcomeDivider: {
    width: 40,
    height: 2,
    backgroundColor: 'rgba(255,255,255,0.3)',
    borderRadius: 1,
    marginVertical: 14,
  },
  welcomeDescription: {
    fontSize: 15,
    color: 'rgba(255,255,255,0.75)',
    textAlign: 'center',
    lineHeight: 23,
    paddingHorizontal: 16,
    maxWidth: 320,
  },
  getStartedButton: {
    backgroundColor: '#ffffff',
    paddingVertical: 17,
    paddingHorizontal: 48,
    borderRadius: 30,
    marginTop: 28,
    shadowColor: 'rgba(0,0,0,0.3)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 6,
    minWidth: 220,
    alignItems: 'center',
  },
  getStartedButtonText: {
    color: colors.brandDark,
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: 0.3,
  },

  // ─── Shared layout for screens 2-5 ────────────────────────
  screenContainer: {
    flex: 1,
    backgroundColor: colors.brandLight,
  },
  screenContent: {
    flex: 1,
    paddingHorizontal: 28,
  },
  headerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 58,
    paddingHorizontal: 20,
    paddingBottom: 8,
  },
  headerBackButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.earthSand,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerBackText: {
    fontSize: 22,
    color: colors.brandDark,
    marginTop: -2,
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.brandPrimary,
    letterSpacing: 0.3,
  },
  headerSkipButton: {
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: colors.earthSand,
  },
  headerSkipText: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.brandPrimary,
  },
  headerSpacer: {
    width: 40,
  },

  // ─── Progress dots ─────────────────────────────────────────
  progressContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 12,
  },
  progressDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.earthSand,
  },
  progressDotActive: {
    width: 24,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.brandAccent,
  },

  // ─── Modi image (smaller, for screens 2-4) ────────────────
  smallPandaWrapper: {
    width: 90,
    height: 90,
    borderRadius: 45,
    overflow: 'hidden',
    alignSelf: 'center',
    marginTop: 8,
    marginBottom: 20,
    borderWidth: 3,
    borderColor: colors.earthSand,
    shadowColor: colors.brandPrimary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 4,
  },
  smallPandaImage: {
    width: '100%',
    height: '100%',
  },

  // ─── Headings & subtitles ─────────────────────────────────
  heading: {
    fontSize: 28,
    fontWeight: '800',
    color: colors.brandDark,
    textAlign: 'center',
    marginBottom: 6,
    letterSpacing: -0.3,
  },
  subtitle: {
    fontSize: 15,
    color: colors.brandPrimary,
    textAlign: 'center',
    marginBottom: 28,
    lineHeight: 21,
  },

  // ─── Name screen input ────────────────────────────────────
  textInputWrapper: {
    marginHorizontal: 4,
  },
  textInputLabel: {
    fontSize: 13,
    fontWeight: '500',
    color: colors.brandPrimary,
    marginBottom: 8,
    marginLeft: 4,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  textInput: {
    backgroundColor: '#ffffff',
    borderWidth: 1.5,
    borderColor: colors.earthSand,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 20,
    fontSize: 17,
    color: colors.brandDark,
  },
  textInputFocused: {
    borderColor: colors.brandAccent,
    shadowColor: colors.brandAccent,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 2,
  },

  // ─── Categories chip grid ─────────────────────────────────
  chipGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 10,
    paddingHorizontal: 4,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 11,
    paddingHorizontal: 18,
    borderRadius: 22,
    backgroundColor: '#ffffff',
    borderWidth: 1.5,
    borderColor: colors.earthSand,
    gap: 6,
  },
  chipSelected: {
    backgroundColor: colors.brandSecondary,
    borderColor: colors.brandSecondary,
  },
  chipText: {
    fontSize: 15,
    color: colors.brandDark,
    fontWeight: '500',
  },
  chipTextSelected: {
    color: '#ffffff',
    fontWeight: '600',
  },
  chipCheckmark: {
    fontSize: 13,
    color: '#ffffff',
    fontWeight: '700',
  },
  chipCount: {
    textAlign: 'center',
    fontSize: 13,
    color: colors.brandPrimary,
    marginTop: 16,
  },

  // ─── Notifications screen ─────────────────────────────────
  notificationCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 18,
    marginHorizontal: 4,
    marginBottom: 28,
    borderWidth: 1,
    borderColor: colors.earthSand,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  notificationCardLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.brandPrimary,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 12,
  },
  notificationPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    backgroundColor: colors.brandLight,
    borderRadius: 14,
    padding: 14,
  },
  notificationIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: colors.brandAccent,
    justifyContent: 'center',
    alignItems: 'center',
  },
  notificationIconText: {
    fontSize: 20,
  },
  notificationTextGroup: {
    flex: 1,
  },
  notificationPreviewTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.brandDark,
  },
  notificationPreviewBody: {
    fontSize: 13,
    color: colors.brandPrimary,
    marginTop: 2,
    fontStyle: 'italic',
  },
  notificationPreviewTime: {
    fontSize: 11,
    color: colors.brandMuted,
    fontWeight: '500',
  },
  frequencySectionLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.brandDark,
    textAlign: 'center',
    marginBottom: 12,
    letterSpacing: 0.2,
  },
  frequencyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 24,
    marginBottom: 24,
  },
  frequencyButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#ffffff',
    borderWidth: 1.5,
    borderColor: colors.earthSand,
    justifyContent: 'center',
    alignItems: 'center',
  },
  frequencyButtonText: {
    fontSize: 22,
    color: colors.brandDark,
    fontWeight: '500',
  },
  frequencyValue: {
    fontSize: 32,
    fontWeight: '800',
    color: colors.brandDark,
    minWidth: 56,
    textAlign: 'center',
    letterSpacing: -0.5,
  },
  frequencyUnit: {
    fontSize: 16,
    fontWeight: '400',
    color: colors.brandPrimary,
  },
  timeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 20,
  },
  timeBlock: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.earthSand,
    paddingVertical: 14,
    paddingHorizontal: 12,
  },
  timeLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.brandPrimary,
    marginBottom: 6,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  timeValue: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.brandDark,
  },
  summaryText: {
    fontSize: 14,
    color: colors.brandPrimary,
    textAlign: 'center',
    lineHeight: 21,
    fontStyle: 'italic',
  },

  // ─── Bottom button (shared for screens 2-5) ───────────────
  bottomButtonContainer: {
    paddingHorizontal: 28,
    paddingBottom: 44,
    paddingTop: 12,
  },
  nextButton: {
    backgroundColor: colors.brandDark,
    paddingVertical: 17,
    borderRadius: 30,
    alignItems: 'center',
    shadowColor: colors.brandDark,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  nextButtonDisabled: {
    backgroundColor: colors.earthSand,
    shadowOpacity: 0,
    elevation: 0,
  },
  nextButtonText: {
    color: '#ffffff',
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  nextButtonTextDisabled: {
    color: colors.brandPrimary,
  },

  // ─── Welcome back screen (Screen 5) ───────────────────────
  welcomeBackContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.brandLight,
    padding: 32,
  },
  welcomeBackDecoration: {
    position: 'absolute',
    top: '30%',
    width: SCREEN_WIDTH * 0.7,
    height: SCREEN_WIDTH * 0.7,
    borderRadius: SCREEN_WIDTH * 0.35,
    backgroundColor: colors.brandAccent,
    opacity: 0.06,
  },
  welcomeBackImageWrapper: {
    width: 120,
    height: 120,
    borderRadius: 60,
    overflow: 'hidden',
    marginBottom: 28,
    borderWidth: 3,
    borderColor: colors.earthSand,
    shadowColor: colors.brandPrimary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 6,
  },
  welcomeBackPandaImage: {
    width: '100%',
    height: '100%',
  },
  welcomeBackTitle: {
    fontSize: 40,
    fontWeight: '800',
    color: colors.brandDark,
    textAlign: 'center',
    marginBottom: 8,
    letterSpacing: -0.5,
  },
  welcomeBackSubtitle: {
    fontSize: 17,
    color: colors.brandPrimary,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  welcomeBackDots: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 24,
  },
  welcomeBackDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.brandAccent,
    opacity: 0.4,
  },
});
